<a href="https://colab.research.google.com/github/kittiporntum1-cell/ADALL_github/blob/main/Tum_Co_pilot_guidance__Copy_of_ADALL_Practical_Test_Revision_Regression_vold2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Practical Test Revision (Regression): Predicting Number of Failed Subjects

This notebook revises a **regression workflow** using a target that is a **special case**:

- Your target is a **count**: number of subjects failed (based on scores below **10** from **G1, G2, G3**).
- Because the target is an **integer count** (often 0, 1, 2, 3), it can *feel* similar to classification.
- However, you are still doing **regression** because the model outputs a **numeric value** and you evaluate using **regression metrics**.

## How to think about this target (important for revision)

| Perspective | What it means here | Typical choice |
|---|---|---|
| Regression view | Predict a numeric count (can be 0–3, but model can output non-integers) | MSE / MAE / RMSE, R² |
| Classification-like view (edge case) | If you convert counts into categories (e.g., 0 vs ≥1) you can classify | Accuracy, F1, ROC-AUC |

### Caveat you must remember
Even when the target behaves like classes, **do not switch to classification** unless the task explicitly asks you to do so.

## Practical test habits
- Keep code **readable** and **step-by-step**.
- Add short notes explaining **why** a step is needed.
- When unsure: print shapes, check missing values, and check your target distribution.

---

STEP 0  Setup

STEP 1  Load Data

STEP 2  Explore Dataset
         df.shape
         df.info()
         df.describe()
         df.isnull().sum()

STEP 3  Dataset Profile
    dataset_profile

Markdown:
    - What the dataset is about
    - Target definition
    - Dataset imbalance
    - Evaluation metric choice

STEP 3A LLM Dataset Reasoning Prompt

STEP 4  LLM assisted problem framing

STEP 5  Context

STEP 6  Instruction

STEP 7  Payload

STEP 8  OpenAI Recommendations

STEP 9  Review Recommendations

STEP 10  Data Cleaning
         - Missing values
         - Duplicates
         - Invalid values
         - Data types
         - Remove leakage columns (if instructed)

STEP 11 Create Target
          y = target

STEP 12 Jitter Plots (Predictor vs Target Analysis)


STEP 13  Train/Test Split

STEP 14 Preprocessing
          - Encoding
          - Scaling
          - ColumnTransformer
          - Pipeline

STEP 15 Baseline Model

STEP 16 Evaluation
          - MAE
          - RMSE
          - R²

STEP 17 Improvements
          - Hyperparameter tuning
          - Feature engineering
          - Compare models

## **Step 0) Setup**

In [17]:
# Core libraries

import os
import shutil
import platform
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib

# Modelling libraries used later in Session 2
from sklearn.model_selection import train_test_split, ShuffleSplit, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor

# Make wide tables easier to read in Colab
pd.set_option('display.max_columns', 100)

# **Step 0A: OpenAI Setup**

In [18]:
from google.colab import userdata
from openai import OpenAI

# load key from Colab Secrets
api_key = userdata.get('OPENAI_API_KEY')

client = OpenAI(
    api_key=api_key
)
print("OpenAI client created successfully.")

OpenAI client created successfully.


#**#Step 1) Load data and do quick checks**

**Goal:** confirm you loaded the correct file, and the dataset looks sensible.

Checklist:
- Use `df.head()` to sanity check columns.
- Use `df.shape` to confirm rows and columns.
- Use `df.info()` to see dtypes and missing values quickly.

If anything looks odd (unexpected columns, too few rows), stop and fix it before modelling.

In [ ]:
# another load dataset template (github)

github_raw_url = 'https://raw.githubusercontent.com/rq-goh/ADALL_github/refs/heads/main/laptop_prices_2024_sgd_TL.csv'

df = pd.read_csv(github_raw_url)

print('Dataset loaded successfully.')
print('Shape:', df.shape)
display(df.head())

In [19]:
# ------------------------------------------------------------
# LOAD DATA (do first) , Template for Kagglehub data set
# Tip: if this block is slow, run it early.
# ------------------------------------------------------------

import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download("devansodariya/student-performance-data")
print("Downloaded to:", path)
print(os.listdir(path))

df = pd.read_csv(os.path.join(path, "student_data.csv"))
df.head()

Using Colab cache for faster access to the 'student-performance-data' dataset.
Downloaded to: /kaggle/input/student-performance-data
['student_data.csv']

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10

In [ ]:
# another load dataset template (csv file)
df = pd.read_csv(...)
print(df.shape)
display(df.head())

# **Step 2: Understand Dataset**

In [20]:
df = pd.read_csv(os.path.join(path, "student_data.csv"))
df.shape # Number of rows & columns

(395, 33)

In [21]:
df.info() #dataset structure

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [22]:
df.describe(include='all')

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395,395,395.000000,395,395,395,395.000000,395.000000,395,395,395,395,395.000000,395.000000,395.000000,395,395,395,395,395,395,395,395,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
unique,2,2,NaN,2,2,2,NaN,NaN,5,5,4,3,NaN,NaN,NaN,2,2,2,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,GP,F,NaN,U,GT3,T,NaN,NaN,other,other,course,mother,NaN,NaN,NaN,no,yes,no,yes,yes,yes,yes,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,349,208,NaN,307,281,354,NaN,NaN,141,217,145,273,NaN,NaN,NaN,344,242,214,201,314,375,329,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,16.696203,NaN,NaN,NaN,2.749367,2.521519,NaN,NaN,NaN,NaN,1.448101,2.035443,0.334177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,NaN,NaN,1.276043,NaN,NaN,NaN,1.094735,1.088201,NaN,NaN,NaN,NaN,0.697505,0.839240,0.743651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,NaN,NaN,15.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,NaN,NaN,16.000000,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN,NaN,NaN,1.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,NaN,NaN,17.000000,NaN,NaN,NaN,3.000000,2.000000,NaN,NaN,NaN,NaN,1.000000,2.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,NaN,NaN,18.000000,NaN,NaN,NaN,4.000000,3.000000,NaN,NaN,NaN,NaN,2.000000,2.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,NaN,NaN,22.000000,NaN,NaN,NaN,4.000000,4.000000,NaN,NaN,NaN,NaN,4.000000,4.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [23]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [24]:
df.columns.tolist()

['school',
 'sex',
 'age',
 'address',
 'famsize',
 'Pstatus',
 'Medu',
 'Fedu',
 'Mjob',
 'Fjob',
 'reason',
 'guardian',
 'traveltime',
 'studytime',
 'failures',
 'schoolsup',
 'famsup',
 'paid',
 'activities',
 'nursery',
 'higher',
 'internet',
 'romantic',
 'famrel',
 'freetime',
 'goout',
 'Dalc',
 'Walc',
 'health',
 'absences',
 'G1',
 'G2',
 'G3']

### What you should write in markdown as you go

In a practical test, you are often graded on your reasoning, not just your code.

As you proceed, add short notes like:
- What does each key column represent in plain words?
- What is your target, and why is it defined this way?
- Is the dataset imbalanced? If yes, what is the impact on evaluation?
- What metric did you choose, and why?

Keep each explanation to **2 to 5 lines**.

###Info about the dataset:

Student Performance Data was obtained in a survey of students' math course in secondary school.
It consists of 33 Column
Dataset Contains Features like:
```
school ID
gender
age
size of family
Father education
Mother education
Occupation of Father and Mother
Family Relation
Health
Grades
```

# **Step 3: Create Dataset Profile**  (Template to be re-used)

In [25]:
dataset_profile = f"""
Dataset Shape:
{df.shape}

Columns:
{list(df.columns)}

Data Types:
{df.dtypes.to_string()}

Missing Values:
{df.isnull().sum().to_string()}

Duplicate Rows:
{df.duplicated().sum()}

Sample Records:
{df.head().to_string()}
"""

print(dataset_profile)

Dataset Shape:
(395, 33)

Columns:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

Data Types:
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64

Missing Values:
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0

Duplicate Rows:
0

Sample Records:
  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason guardian  traveltime  studytime  failures schoolsup famsup paid activities nursery higher internet romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  course   mother           2          2         0       yes     no   no         no     yes    yes       no       no       4         3      4     1     1       3         6   5   6   6
1     GP   F   17       U     GT3       T     1     1  at_home     other  course   father           1          2         0        no    yes   no         no      no    yes      yes       no       5         3      3     1     1       3         4   5   5   6
2     GP   F   15       U     LE3       T     1     1  at_home     other   other   mother           1          2         3       yes     no  yes         no     yes    yes      yes       no       4         3      2     2     3       3        10   7   8  10
3     GP   F   15       U     GT3       T     4     2   health  services    home   mother           1          3         0        no    yes  yes        yes     yes    yes      yes      yes       3         2      2     1     1       5         2  15  14  15
4     GP   F   16       U     GT3       T     3     3    other     other    home   father           1          2         0        no    yes  yes         no     yes    yes       no       no       4         3      2     1     2       5         4   6  10  10

# **Short Text (Use in practical test)**: Explanation: A text-based dataset profile was created to summarise the dataset structure, size, columns, data types, missing values, duplicate records and sample observations. This provides a concise overview of the dataset before machine learning modelling.

In [10]:
# Mr.Zaw payload template ####
# Build payload text step by step.
# Payload text is a short profile of the dataset.
# It is safer and smaller than sending the full dataset to the LLM.

payload_text = ''

# 1. Shape
payload_text += '=== SHAPE ===\n'
payload_text += 'Rows: ' + str(df.shape[0]) + '\n'
payload_text += 'Columns: ' + str(df.shape[1]) + '\n\n'

# 2. Column names and data types
payload_text += '=== COLUMNS AND DATA TYPES ===\n'
payload_text += df.dtypes.to_string()
payload_text += '\n\n'

# 3. Numeric summary
payload_text += '=== NUMERIC SUMMARY ===\n'
numeric_summary = df.describe(include='number').round(2)
payload_text += numeric_summary.to_string()
payload_text += '\n\n'

# 4. Missing values
payload_text += '=== MISSING VALUES ===\n'
missing_table = pd.DataFrame()
missing_table['missing_count'] = df.isna().sum()
missing_table['missing_pct'] = (df.isna().sum() / len(df) * 100).round(2)
payload_text += missing_table.to_string()
payload_text += '\n\n'

# 5. Unique values per column
payload_text += '=== UNIQUE VALUES PER COLUMN ===\n'
unique_table = pd.DataFrame()
unique_table['unique_count'] = df.nunique(dropna=False)
payload_text += unique_table.to_string()
payload_text += '\n\n'

# 6. Correlation between numeric columns
payload_text += '=== CORRELATION BETWEEN NUMERIC COLUMNS ===\n'
correlation_table = df.corr(numeric_only=True).round(2)
payload_text += correlation_table.to_string()
payload_text += '\n\n'

# 7. Top 10 values for categorical columns
payload_text += '=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===\n'

categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

if len(categorical_columns) == 0:
    payload_text += 'No categorical columns found.\n'
else:
    for col in categorical_columns:
        payload_text += '\nColumn: ' + col + '\n'
        payload_text += df[col].value_counts(dropna=False).head(10).to_string()
        payload_text += '\n'

payload_text += '\n'

# 8. Simple warning checks
payload_text += '=== SIMPLE WARNING CHECKS ===\n'

id_like_columns = []
constant_columns = []

for col in df.columns:
    unique_count = df[col].nunique(dropna=False)

    if unique_count == len(df):
        id_like_columns.append(col)

    if unique_count <= 1:
        constant_columns.append(col)

payload_text += 'Possible ID-like columns: ' + str(id_like_columns) + '\n'
payload_text += 'Constant columns: ' + str(constant_columns) + '\n'
payload_text += 'Duplicate rows: ' + str(df.duplicated().sum()) + '\n'

print(payload_text)

# This cell builds a short dataset profile called payload_text.
# Instead of sending the full dataset to the LLM, we send summary information only.
# The payload includes shape, column types, numeric summary, missing values, unique counts, correlations, and common category values.
# It also adds simple warning checks for possible ID-like columns, constant columns, and duplicate rows.
# This helps the LLM comment on data readiness without needing every row of the dataset.

=== SHAPE ===
Rows: 395
Columns: 33

=== COLUMNS AND DATA TYPES ===
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64

=== NUMERIC SUMMARY ===
          age    Medu    Fedu  traveltime  studytime  failures  famrel  freetime   goout    Dalc    Walc  health  absences      G1      G2      G3
count  395.00  395.00  395.00      395.00     395.00    395.00  395.00    395.00  395.00  395.00  395.00  395.00    395.00  395.00  395.00  395.00
mean    16.70    2.75    2.52        1.45       2.04      0.33    3.94      3.24    3.11    1.48    2.29    3.55      5.71   10.91   10.71   10.42
std      1.28    1.09    1.09        0.70       0.84      0.74    0.90      1.00    1.11    0.89    1.29    1.39      8.00    3.32    3.76    4.58
min     15.00    0.00    0.00        1.00       1.00      0.00    1.00      1.00    1.00    1.00    1.00    1.00      0.00    3.00    0.00    0.00
25%     16.00    2.00    2.00        1.00       1.00      0.00    4.00      3.00    2.00    1.00    1.00    3.00      0.00    8.00    9.00    8.00
50%     17.00    3.00    2.00        1.00       2.00      0.00    4.00      3.00    3.00    1.00    2.00    4.00      4.00   11.00   11.00   11.00
75%     18.00    4.00    3.00        2.00       2.00      0.00    5.00      4.00    4.00    2.00    3.00    5.00      8.00   13.00   13.00   14.00
max     22.00    4.00    4.00        4.00       4.00      3.00    5.00      5.00    5.00    5.00    5.00    5.00     75.00   19.00   19.00   20.00

=== MISSING VALUES ===
            missing_count  missing_pct
school                  0          0.0
sex                     0          0.0
age                     0          0.0
address                 0          0.0
famsize                 0          0.0
Pstatus                 0          0.0
Medu                    0          0.0
Fedu                    0          0.0
Mjob                    0          0.0
Fjob                    0          0.0
reason                  0          0.0
guardian                0          0.0
traveltime              0          0.0
studytime               0          0.0
failures                0          0.0
schoolsup               0          0.0
famsup                  0          0.0
paid                    0          0.0
activities              0          0.0
nursery                 0          0.0
higher                  0          0.0
internet                0          0.0
romantic                0          0.0
famrel                  0          0.0
freetime                0          0.0
goout                   0          0.0
Dalc                    0          0.0
Walc                    0          0.0
health                  0          0.0
absences                0          0.0
G1                      0          0.0
G2                      0          0.0
G3                      0          0.0

=== UNIQUE VALUES PER COLUMN ===
            unique_count
school                 2
sex                    2
age                    8
address                2
famsize                2
Pstatus                2
Medu                   5
Fedu                   5
Mjob                   5
Fjob                   5
reason                 4
guardian               3
traveltime             4
studytime              4
failures               4
schoolsup              2
famsup                 2
paid                   2
activities             2
nursery                2
higher                 2
internet               2
romantic               2
famrel                 5
freetime               5
goout                  5
Dalc                   5
Walc                   5
health                 5
absences              34
G1                    17
G2                    17
G3                    18

=== CORRELATION BETWEEN NUMERIC COLUMNS ===
             age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  Dalc  Walc  health  absences    G1    G2    G3
age         1.00 -0.16 -0.16        0.07      -0.00      0.24    0.05      0.02   0.13  0.13  0.12   -0.06      0.18 -0.06 -0.14 -0.16
Medu       -0.16  1.00  0.62       -0.17       0.06     -0.24   -0.00      0.03   0.06  0.02 -0.05   -0.05      0.10  0.21  0.22  0.22
Fedu       -0.16  0.62  1.00       -0.16      -0.01     -0.25   -0.00     -0.01   0.04  0.00 -0.01    0.01      0.02  0.19  0.16  0.15
traveltime  0.07 -0.17 -0.16        1.00      -0.10      0.09   -0.02     -0.02   0.03  0.14  0.13    0.01     -0.01 -0.09 -0.15 -0.12
studytime  -0.00  0.06 -0.01       -0.10       1.00     -0.17    0.04     -0.14  -0.06 -0.20 -0.25   -0.08     -0.06  0.16  0.14  0.10
failures    0.24 -0.24 -0.25        0.09      -0.17      1.00   -0.04      0.09   0.12  0.14  0.14    0.07      0.06 -0.35 -0.36 -0.36
famrel      0.05 -0.00 -0.00       -0.02       0.04     -0.04    1.00      0.15   0.06 -0.08 -0.11    0.09     -0.04  0.02 -0.02  0.05
freetime    0.02  0.03 -0.01       -0.02      -0.14      0.09    0.15      1.00   0.29  0.21  0.15    0.08     -0.06  0.01 -0.01  0.01
goout       0.13  0.06  0.04        0.03      -0.06      0.12    0.06      0.29   1.00  0.27  0.42   -0.01      0.04 -0.15 -0.16 -0.13
Dalc        0.13  0.02  0.00        0.14      -0.20      0.14   -0.08      0.21   0.27  1.00  0.65    0.08      0.11 -0.09 -0.06 -0.05
Walc        0.12 -0.05 -0.01        0.13      -0.25      0.14   -0.11      0.15   0.42  0.65  1.00    0.09      0.14 -0.13 -0.08 -0.05
health     -0.06 -0.05  0.01        0.01      -0.08      0.07    0.09      0.08  -0.01  0.08  0.09    1.00     -0.03 -0.07 -0.10 -0.06
absences    0.18  0.10  0.02       -0.01      -0.06      0.06   -0.04     -0.06   0.04  0.11  0.14   -0.03      1.00 -0.03 -0.03  0.03
G1         -0.06  0.21  0.19       -0.09       0.16     -0.35    0.02      0.01  -0.15 -0.09 -0.13   -0.07     -0.03  1.00  0.85  0.80
G2         -0.14  0.22  0.16       -0.15       0.14     -0.36   -0.02     -0.01  -0.16 -0.06 -0.08   -0.10     -0.03  0.85  1.00  0.90
G3         -0.16  0.22  0.15       -0.12       0.10     -0.36    0.05      0.01  -0.13 -0.05 -0.05   -0.06      0.03  0.80  0.90  1.00

=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===

Column: school
school
GP    349
MS     46

Column: sex
sex
F    208
M    187

Column: address
address
U    307
R     88

Column: famsize
famsize
GT3    281
LE3    114

Column: Pstatus
Pstatus
T    354
A     41

Column: Mjob
Mjob
other       141
services    103
at_home      59
teacher      58
health       34

Column: Fjob
Fjob
other       217
services    111
teacher      29
at_home      20
health       18

Column: reason
reason
course        145
home          109
reputation    105
other          36

Column: guardian
guardian
mother    273
father     90
other      32

Column: schoolsup
schoolsup
no     344
yes     51

Column: famsup
famsup
yes    242
no     153

Column: paid
paid
no     214
yes    181

Column: activities
activities
yes    201
no     194

Column: nursery
nursery
yes    314
no      81

Column: higher
higher
yes    375
no      20

Column: internet
internet
yes    329
no      66

Column: romantic
romantic
no     263
yes    132

=== SIMPLE WARNING CHECKS ===
Possible ID-like columns: []
Constant columns: []
Duplicate rows: 0

In [26]:
# Tum payload template  ******* Use this **********************
from io import StringIO

# ==========================================
# CHANGE ONLY THIS LINE
# ==========================================

target_column = None

# Example when target is known:
# target_column = "Price"

# ==========================================

buffer = StringIO()

# DATA TYPES
buffer.write("=== DATA TYPES ===\n")
buffer.write(df.dtypes.to_string())
buffer.write("\n\n")

# SHAPE
buffer.write("=== DATASET SHAPE ===\n")
buffer.write(f"Rows: {df.shape[0]}\n")
buffer.write(f"Columns: {df.shape[1]}\n\n")

# TARGET
buffer.write("=== TARGET COLUMN ===\n")

if target_column is None:
    buffer.write("Target not yet specified.\n")
else:
    buffer.write(f"Target: {target_column}\n")

    if target_column in df.columns:
        buffer.write(f"Data Type: {df[target_column].dtype}\n")
        buffer.write(
            f"Unique Values: {df[target_column].nunique(dropna=False)}\n"
        )

buffer.write("\n")

# MISSING VALUES
buffer.write("=== MISSING VALUES ===\n")

missing_summary = (
    df.isna()
      .sum()
      .to_frame("missing_count")
      .assign(
          missing_pct=lambda x:
          (x["missing_count"] / len(df) * 100).round(2)
      )
)

buffer.write(missing_summary.to_string())
buffer.write("\n\n")

# DUPLICATES
buffer.write("=== DUPLICATE ROWS ===\n")
buffer.write(str(df.duplicated().sum()))
buffer.write("\n\n")

# NUMERIC SUMMARY
buffer.write("=== NUMERIC SUMMARY ===\n")

try:
    buffer.write(
        df.describe(include="number")
          .round(3)
          .to_string()
    )
except:
    buffer.write("No numeric columns.")

buffer.write("\n\n")

# CATEGORICAL SUMMARY
buffer.write("=== CATEGORICAL SUMMARY ===\n")

try:
    buffer.write(
        df.describe(include=["object","category"])
          .to_string()
    )
except:
    buffer.write("No categorical columns.")

buffer.write("\n\n")

# UNIQUE VALUES
buffer.write("=== UNIQUE VALUES PER COLUMN ===\n")

buffer.write(
    df.nunique(dropna=False)
      .to_frame("unique_count")
      .to_string()
)

buffer.write("\n\n")

# CONSTANT COLUMNS
buffer.write("=== CONSTANT COLUMNS ===\n")

constant_cols = list(
    df.columns[
        df.nunique(dropna=False) <= 1
    ]
)

buffer.write(str(constant_cols))
buffer.write("\n\n")

# POTENTIAL ID COLUMNS
buffer.write("=== POTENTIAL ID COLUMNS ===\n")

id_cols = list(
    df.columns[
        df.nunique(dropna=False) == len(df)
    ]
)

buffer.write(str(id_cols))
buffer.write("\n\n")

# CORRELATION
buffer.write("=== CORRELATION MATRIX ===\n")

try:

    corr_matrix = (
        df.corr(numeric_only=True)
          .round(3)
    )

    if len(corr_matrix) > 0:
        buffer.write(corr_matrix.to_string())
    else:
        buffer.write("No numeric columns available.")

except Exception as e:
    buffer.write(str(e))

buffer.write("\n\n")

# TOP CATEGORICAL VALUES
buffer.write("=== TOP VALUES FOR CATEGORICAL COLUMNS ===\n")

cat_cols = df.select_dtypes(
    include=["object","category"]
).columns

if len(cat_cols) == 0:
    buffer.write("No categorical columns found.\n")

else:

    for col in cat_cols:

        buffer.write(f"\nColumn: {col}\n")

        buffer.write(
            df[col]
              .value_counts(dropna=False)
              .head(10)
              .to_string()
        )

        buffer.write("\n")

buffer.write("\n")

# SAMPLE ROWS
buffer.write("=== SAMPLE ROWS ===\n")
buffer.write(df.head().to_string())

payload_text = buffer.getvalue()

print(payload_text)

=== DATA TYPES ===
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64

=== DATASET SHAPE ===
Rows: 395
Columns: 33

=== TARGET COLUMN ===
Target not yet specified.

=== MISSING VALUES ===
            missing_count  missing_pct
school                  0          0.0
sex                     0          0.0
age                     0          0.0
address                 0          0.0
famsize                 0          0.0
Pstatus                 0          0.0
Medu                    0          0.0
Fedu                    0          0.0
Mjob                    0          0.0
Fjob                    0          0.0
reason                  0          0.0
guardian                0          0.0
traveltime              0          0.0
studytime               0          0.0
failures                0          0.0
schoolsup               0          0.0
famsup                  0          0.0
paid                    0          0.0
activities              0          0.0
nursery                 0          0.0
higher                  0          0.0
internet                0          0.0
romantic                0          0.0
famrel                  0          0.0
freetime                0          0.0
goout                   0          0.0
Dalc                    0          0.0
Walc                    0          0.0
health                  0          0.0
absences                0          0.0
G1                      0          0.0
G2                      0          0.0
G3                      0          0.0

=== DUPLICATE ROWS ===
0

=== NUMERIC SUMMARY ===
           age     Medu     Fedu  traveltime  studytime  failures   famrel  freetime    goout     Dalc     Walc   health  absences       G1       G2       G3
count  395.000  395.000  395.000     395.000    395.000   395.000  395.000   395.000  395.000  395.000  395.000  395.000   395.000  395.000  395.000  395.000
mean    16.696    2.749    2.522       1.448      2.035     0.334    3.944     3.235    3.109    1.481    2.291    3.554     5.709   10.909   10.714   10.415
std      1.276    1.095    1.088       0.698      0.839     0.744    0.897     0.999    1.113    0.891    1.288    1.390     8.003    3.319    3.762    4.581
min     15.000    0.000    0.000       1.000      1.000     0.000    1.000     1.000    1.000    1.000    1.000    1.000     0.000    3.000    0.000    0.000
25%     16.000    2.000    2.000       1.000      1.000     0.000    4.000     3.000    2.000    1.000    1.000    3.000     0.000    8.000    9.000    8.000
50%     17.000    3.000    2.000       1.000      2.000     0.000    4.000     3.000    3.000    1.000    2.000    4.000     4.000   11.000   11.000   11.000
75%     18.000    4.000    3.000       2.000      2.000     0.000    5.000     4.000    4.000    2.000    3.000    5.000     8.000   13.000   13.000   14.000
max     22.000    4.000    4.000       4.000      4.000     3.000    5.000     5.000    5.000    5.000    5.000    5.000    75.000   19.000   19.000   20.000

=== CATEGORICAL SUMMARY ===
       school  sex address famsize Pstatus   Mjob   Fjob  reason guardian schoolsup famsup paid activities nursery higher internet romantic
count     395  395     395     395     395    395    395     395      395       395    395  395        395     395    395      395      395
unique      2    2       2       2       2      5      5       4        3         2      2    2          2       2      2        2        2
top        GP    F       U     GT3       T  other  other  course   mother        no    yes   no        yes     yes    yes      yes       no
freq      349  208     307     281     354    141    217     145      273       344    242  214        201     314    375      329      263

=== UNIQUE VALUES PER COLUMN ===
            unique_count
school                 2
sex                    2
age                    8
address                2
famsize                2
Pstatus                2
Medu                   5
Fedu                   5
Mjob                   5
Fjob                   5
reason                 4
guardian               3
traveltime             4
studytime              4
failures               4
schoolsup              2
famsup                 2
paid                   2
activities             2
nursery                2
higher                 2
internet               2
romantic               2
famrel                 5
freetime               5
goout                  5
Dalc                   5
Walc                   5
health                 5
absences              34
G1                    17
G2                    17
G3                    18

=== CONSTANT COLUMNS ===
[]

=== POTENTIAL ID COLUMNS ===
[]

=== CORRELATION MATRIX ===
              age   Medu   Fedu  traveltime  studytime  failures  famrel  freetime  goout   Dalc   Walc  health  absences     G1     G2     G3
age         1.000 -0.164 -0.163       0.071     -0.004     0.244   0.054     0.016  0.127  0.131  0.117  -0.062     0.175 -0.064 -0.143 -0.162
Medu       -0.164  1.000  0.623      -0.172      0.065    -0.237  -0.004     0.031  0.064  0.020 -0.047  -0.047     0.100  0.205  0.216  0.217
Fedu       -0.163  0.623  1.000      -0.158     -0.009    -0.250  -0.001    -0.013  0.043  0.002 -0.013   0.015     0.024  0.190  0.165  0.152
traveltime  0.071 -0.172 -0.158       1.000     -0.101     0.092  -0.017    -0.017  0.029  0.138  0.134   0.008    -0.013 -0.093 -0.153 -0.117
studytime  -0.004  0.065 -0.009      -0.101      1.000    -0.174   0.040    -0.143 -0.064 -0.196 -0.254  -0.076    -0.063  0.161  0.136  0.098
failures    0.244 -0.237 -0.250       0.092     -0.174     1.000  -0.044     0.092  0.125  0.136  0.142   0.066     0.064 -0.355 -0.356 -0.360
famrel      0.054 -0.004 -0.001      -0.017      0.040    -0.044   1.000     0.151  0.065 -0.078 -0.113   0.094    -0.044  0.022 -0.018  0.051
freetime    0.016  0.031 -0.013      -0.017     -0.143     0.092   0.151     1.000  0.285  0.209  0.148   0.076    -0.058  0.013 -0.014  0.011
goout       0.127  0.064  0.043       0.029     -0.064     0.125   0.065     0.285  1.000  0.267  0.420  -0.010     0.044 -0.149 -0.162 -0.133
Dalc        0.131  0.020  0.002       0.138     -0.196     0.136  -0.078     0.209  0.267  1.000  0.648   0.077     0.112 -0.094 -0.064 -0.055
Walc        0.117 -0.047 -0.013       0.134     -0.254     0.142  -0.113     0.148  0.420  0.648  1.000   0.092     0.136 -0.126 -0.085 -0.052
health     -0.062 -0.047  0.015       0.008     -0.076     0.066   0.094     0.076 -0.010  0.077  0.092   1.000    -0.030 -0.073 -0.098 -0.061
absences    0.175  0.100  0.024      -0.013     -0.063     0.064  -0.044    -0.058  0.044  0.112  0.136  -0.030     1.000 -0.031 -0.032  0.034
G1         -0.064  0.205  0.190      -0.093      0.161    -0.355   0.022     0.013 -0.149 -0.094 -0.126  -0.073    -0.031  1.000  0.852  0.801
G2         -0.143  0.216  0.165      -0.153      0.136    -0.356  -0.018    -0.014 -0.162 -0.064 -0.085  -0.098    -0.032  0.852  1.000  0.905
G3         -0.162  0.217  0.152      -0.117      0.098    -0.360   0.051     0.011 -0.133 -0.055 -0.052  -0.061     0.034  0.801  0.905  1.000

=== TOP VALUES FOR CATEGORICAL COLUMNS ===

Column: school
school
GP    349
MS     46

Column: sex
sex
F    208
M    187

Column: address
address
U    307
R     88

Column: famsize
famsize
GT3    281
LE3    114

Column: Pstatus
Pstatus
T    354
A     41

Column: Mjob
Mjob
other       141
services    103
at_home      59
teacher      58
health       34

Column: Fjob
Fjob
other       217
services    111
teacher      29
at_home      20
health       18

Column: reason
reason
course        145
home          109
reputation    105
other          36

Column: guardian
guardian
mother    273
father     90
other      32

Column: schoolsup
schoolsup
no     344
yes     51

Column: famsup
famsup
yes    242
no     153

Column: paid
paid
no     214
yes    181

Column: activities
activities
yes    201
no     194

Column: nursery
nursery
yes    314
no      81

Column: higher
higher
yes    375
no      20

Column: internet
internet
yes    329
no      66

Column: romantic
romantic
no     263
yes    132

=== SAMPLE ROWS ===
  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  reason guardian  traveltime  studytime  failures schoolsup famsup paid activities nursery higher internet romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  course   mother           2          2         0       yes     no   no         no     yes    yes       no       no       4         3      4     1     1       3         6   5   6   6
1     GP   F   17       U     GT3       T     1     1  at_home     other  course   father           1          2         0        no    yes   no         no      no    yes      yes       no       5         3      3     1     1       3         4   5   5   6
2     GP   F   15       U     LE3       T     1     1  at_home     other   other   mother           1          2         3       yes     no  yes         no     yes    yes      yes       no       4         3      2     2     3       3        10   7   8  10
3     GP   F   15       U     GT3       T     4     2   health  services    home   mother           1          3         0        no    yes  yes        yes     yes    yes      yes      yes       3         2      2     1     1       5         2  15  14  15
4     GP   F   16       U     GT3       T     3     3    other     other    home   father           1          2         0        no    yes  yes         no     yes    yes       no       no       4         3      2     1     2       5         4   6  10  10


Dataset profile (no charts yet)

**Why this matters:** In a practical test, you should be able to describe your dataset without relying on charts.

Focus on:
- which columns are numeric vs categorical,
- missing values (how many, where),
- target column (what type it is, what values it takes).

Write your observations as short bullet points in your report.

###Mock question (revision of steps you have already practised)

1. Create a text-based payload that clearly describes the dataset.
The description should summarise the dataset structure, key columns, size, and any notable data issues.

2. Then, send this payload to the OpenAI API together with:

>>clear context about the task, and
>>
>>a concise instruction telling the model what you want it to do with the dataset information.

The following block shows an example in image form for revision purposes.

# **Step3 (A): LLM Dataset Reasoning Prompt**

Can skip this step if no need.

In [27]:
# Prompt 1: LLM Dataset Reasoning Prompt

reasoning_prompt = f"""
You are a senior data scientist preparing a practical-test report.

Dataset Profile:

{payload_text}

Please provide concise reasoning suitable for a markdown report.

Answer the following:

1. What does this dataset appear to contain?

2. Explain the key columns in plain business language.

3. What is the most likely target variable?
   - Explain why.
   - State whether the target is numeric or categorical.

4. Is the target likely to be balanced or imbalanced?
   - Explain the possible impact on model evaluation.

5. Is this likely to be a Regression or Classification problem?
   - Explain why.

6. Which evaluation metric(s) would be appropriate?
   - Explain why.

7. Summarise:
   - Numeric columns
   - Categorical columns
   - Missing values
   - Potential data-quality issues

Requirements:

- Keep each answer between 2 and 5 lines.
- Use practical business language.
- Use markdown bullet points.
- Avoid technical jargon where possible.
- Be suitable for a practical-test submission.
"""

reasoning_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
    You are helping a student prepare concise markdown observations for a data analytics practical test.

    Keep the answers short, practical and easy for a lecturer to mark.

    Do not provide multiple alternatives.
    Choose the most likely answer.
    """,
    input=reasoning_prompt
)

print(reasoning_response.output_text)

- **1) What does this dataset appear to contain?**
  - Student survey/administrative data about secondary school learners.
  - Includes background (family, address, guardian), school context, study habits, lifestyle, attendance, and academic results.
  - Likely used to predict **student performance**.

- **2) Explain key columns in plain business language**
  - **Background:** `sex`, `age`, `address` (urban/rural), `famsize`, `Pstatus`, `guardian`, parents’ education (`Medu`, `Fedu`).
  - **School/study behavior:** `studytime`, `schoolsup`, `famsup`, `paid`, `internet`, `nursery`, `higher`, `activities`.
  - **Lifestyle/attendance & performance signals:** drinking (`Dalc`, `Walc`), time away (`goout`), well-being (`health`), and `absences`, plus grades (`G1`, `G2`, `G3`).

- **3) Most likely target variable**
  - **Target: `G3` (final grade)**. It represents the final academic outcome and is the most direct “end result” column.
  - It is **numeric** (integer grade), shown as a continuous score range in the numeric summary.

- **4) Balanced or imbalanced?**
  - Likely **imbalanced** because grades tend to cluster around mid/high values (most students scoring similarly), not evenly across all possible scores.
  - If imbalanced, accuracy can be misleading and some score ranges may be poorly predicted, lowering real-world usefulness.

- **5) Regression or classification?**
  - **Regression**, because the target `G3` is a numeric score (not a fixed category like pass/fail).
  - The dataset also includes earlier numeric grades (`G1`, `G2`) that naturally predict a numeric outcome.

- **6) Appropriate evaluation metrics**
  - **MAE (Mean Absolute Error):** easy to interpret as average grade error.
  - **RMSE (Root Mean Squared Error):** penalizes large mistakes more, important for avoiding very inaccurate grade predictions.
  - (Optional) **R²** to show how much of the grade variation is explained.

- **7) Summary**
  - **Numeric columns:** `age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3` (plus counts/rating scales).
  - **Categorical columns:** `school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardian, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic`.
  - **Missing values:** **none** (0 across all columns).
  - **Potential data-quality issues:** `absences` has a high max (75) → possible outliers; grading scales are integer-coded, so ensure consistent handling (and avoid treating grades as categories).

In [8]:
# Prompt 2: LLM Dataset Reasoning Prompt (Can skip this step if no need.)

reasoning_prompt = f"""
You are a senior data scientist preparing a practical-test report.

Dataset Profile:

{dataset_profile}

Please provide concise reasoning suitable for a markdown report.

Answer the following:
1. How many rows and columns there are.
2. What the first few rows look like.
3. Which columns are numeric or categorical.
4. Whether any obvious data quality issue appears.
5. Which column are we trying to predict?
6. Which columns look numeric?
7. Which columns look categorical?
8. Do you see any columns that may be discounts, IDs, or repeated constants?

This is a quick orientation step, not a full analysis.
"""

reasoning_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
You are helping a student prepare concise markdown observations for a data analytics practical test.

Keep the answers short, practical and easy for a lecturer to mark.

Do not provide multiple alternatives.
Choose the most likely answer.
""",
    input=reasoning_prompt
)

print(reasoning_response.output_text)

### 1) Rows and columns
- **Rows:** 395
- **Columns:** 33

### 2) First few rows (what they look like)
- Dataset is a **mixed-type tabular student performance** dataset.
- Example columns shown: `school`, `sex`, `age`, `address`, family/guardian fields, school-related indicators (e.g., `studytime`, `internet`), and grades `G1`, `G2`, `G3`.
- Sample row 0 includes: `school=GP`, `sex=F`, `age=18`, `famsize=GT3`, `Medu=4`, `Fedu=4`, and finishes with grades like `G1=6, G2=5, G3=6`.

### 3) Numeric vs categorical columns
**Numeric (int64):**
`age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3`

**Categorical (object):**
`school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardian, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic`

### 4) Obvious data quality issues
- **No missing values** (all columns show 0 missing).
- **No duplicate rows**.
- Main potential “issue” to watch later (not a current flaw): many categorical variables are **binary** stored as objects (e.g., `yes/no`), which may need consistent encoding.

### 5) Target (what we are trying to predict)
- **`G3`** (final grade) is the most likely prediction target (typical setup alongside `G1` and `G2`).

### 6) Columns that look numeric
`age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3`

### 7) Columns that look categorical
`school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardian, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic`

### 8) Possible IDs / discounts / repeated constants
- **No obvious ID columns** present (no `id`, `student_id`, etc.).
- No clear “discount” fields.
- No constant columns are visible from the provided info; however, many category fields may be **low-cardinality** (e.g., yes/no), which can appear “repeated” but is not an ID.

# **Step 4: LLM assisted problem framing**

# **Find the Target column**

In [28]:
problem_framing_prompt = f"""

You are a senior business analytics consultant.

Using the dataset information below, translate the dataset into a clear business problem and modelling objective.

Dataset Information:

{payload_text}

Requirements:

1. Write the BUSINESS PROBLEM in simple business language.
   - Do not mention machine learning, algorithms, features or predictors.
   - Focus on the real-world problem the organisation wants to solve.

2. Write the MODELLING OBJECTIVE in technical language.
   - State exactly what the model should predict.
   - State whether it is Regression or Classification.
   - Choose ONE best answer only.

3. Identify:
   - Target variable
   - Evaluation metric & Reason behind
   - Main stakeholders
   - Business value
   - Key risks

Keep answers concise.

Use exactly this format:

Business Problem:
...

Modelling Objective:
...

Target:
...

Problem Type:
Regression / Classification

Metric:
...

Stakeholders:
...

Business Value:
...

Risks:
...
"""

problem_framing_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
    You are a senior business analytics consultant.

    Translate business problems into machine learning objectives.

    Keep answers concise and practical.
    """,
    input=problem_framing_prompt
)

print(problem_framing_response.output_text)

Business Problem:
A school board wants to identify which students are at higher risk of underperforming academically so it can prioritize academic support (tutoring, interventions, and mentoring) early in the term and reduce the number of students who fall below expected grade levels.

Modelling Objective:
Build a model to predict the student’s final achievement score (G3) for each enrolled student, using their prior term performance and background/behavioral information available at the time of prediction. The model should output a continuous estimate of G3.

Target:
G3 (final grade)

Problem Type:
Regression

Metric:
Mean Absolute Error (MAE) — it measures the average absolute deviation between predicted and actual final grades, is intuitive for school performance (grade-point units), and is more robust than RMSE to outliers.

Stakeholders:
Students and parents; teachers and academic support staff; school principals; education operations/program managers; school board decision-makers.

Business Value:
More accurate early identification of students likely to score poorly, enabling targeted interventions, better allocation of limited tutoring/support resources, and improved overall pass/achievement rates.

Risks:
Label leakage or timing mismatch (using information that wouldn’t be available at intervention time); data bias (riskier groups may be disproportionately flagged); model instability across school types if distributions differ; potential fairness concerns and misinterpretation of predictions leading to inappropriate support or stigma.

# **Step 5: Create Context**

In [11]:
context = """

You are an expert data scientist specialising in machine learning preprocessing and tree-based models.

Only use evidence provided in the dataset profile.

Do not guess information that is not present.

Do not perform encoding, scaling, feature selection, train/test split, modelling or evaluation.

Focus only on data understanding, data quality assessment and data cleaning preparation.

"""

# **Step 6: Create Instruction**

In [12]:
instruction = """

TASK

Review the dataset profile and identify:

1. Data quality issues.
2. Missing value concerns.
3. Duplicate record concerns.
4. Potential outlier concerns.
5. ID-like columns.
6. Constant or near-constant columns.
7. Redundant or highly correlated columns.
8. Potential target leakage or label leakage risks.
9. Data type issues.
10. Feature engineering opportunities.
11. Columns that may be candidates for removal before modelling.

For every issue provide:

- Issue
- Evidence from dataset profile
- Why it matters
- ML impact
- Recommended action
- Priority (High / Medium / Low)

Important:

- Do not recommend dropping a column solely because it appears in warning checks.
- Explain why before recommending removal.
- If evidence is insufficient, state:
  'Cannot be confirmed from dataset profile alone.'

Finally provide:

A. Data Quality Review
B. Recommended Actions
C. Suggested Cleaning Steps (in order)

Keep the answer concise but complete.
"""

# **Step 7: Create Final Payload**

In [13]:
outcome = f"""
CONTEXT:
{context}

DATASET INFORMATION:
{payload_text}

TASK:
{instruction}
"""

print(outcome)

CONTEXT:


You are an expert data scientist specialising in machine learning preprocessing and tree-based models.

Only use evidence provided in the dataset profile.

Do not guess information that is not present.

Do not perform encoding, scaling, feature selection, train/test split, modelling or evaluation.

Focus only on data understanding, data quality assessment and data cleaning preparation.



DATASET INFORMATION:
=== SHAPE ===
Rows: 395
Columns: 33

=== COLUMNS AND DATA TYPES ===
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64

=== NUMERIC SUMMARY ===
          age    Medu    Fedu  traveltime  studytime  failures  famrel  freetime   goout    Dalc    Walc  health  absences      G1      G2      G3
count  395.00  395.00  395.00      395.00     395.00    395.00  395.00    395.00  395.00  395.00  395.00  395.00    395.00  395.00  395.00  395.00
mean    16.70    2.75    2.52        1.45       2.04      0.33    3.94      3.24    3.11    1.48    2.29    3.55      5.71   10.91   10.71   10.42
std      1.28    1.09    1.09        0.70       0.84      0.74    0.90      1.00    1.11    0.89    1.29    1.39      8.00    3.32    3.76    4.58
min     15.00    0.00    0.00        1.00       1.00      0.00    1.00      1.00    1.00    1.00    1.00    1.00      0.00    3.00    0.00    0.00
25%     16.00    2.00    2.00        1.00       1.00      0.00    4.00      3.00    2.00    1.00    1.00    3.00      0.00    8.00    9.00    8.00
50%     17.00    3.00    2.00        1.00       2.00      0.00    4.00      3.00    3.00    1.00    2.00    4.00      4.00   11.00   11.00   11.00
75%     18.00    4.00    3.00        2.00       2.00      0.00    5.00      4.00    4.00    2.00    3.00    5.00      8.00   13.00   13.00   14.00
max     22.00    4.00    4.00        4.00       4.00      3.00    5.00      5.00    5.00    5.00    5.00    5.00     75.00   19.00   19.00   20.00

=== MISSING VALUES ===
            missing_count  missing_pct
school                  0          0.0
sex                     0          0.0
age                     0          0.0
address                 0          0.0
famsize                 0          0.0
Pstatus                 0          0.0
Medu                    0          0.0
Fedu                    0          0.0
Mjob                    0          0.0
Fjob                    0          0.0
reason                  0          0.0
guardian                0          0.0
traveltime              0          0.0
studytime               0          0.0
failures                0          0.0
schoolsup               0          0.0
famsup                  0          0.0
paid                    0          0.0
activities              0          0.0
nursery                 0          0.0
higher                  0          0.0
internet                0          0.0
romantic                0          0.0
famrel                  0          0.0
freetime                0          0.0
goout                   0          0.0
Dalc                    0          0.0
Walc                    0          0.0
health                  0          0.0
absences                0          0.0
G1                      0          0.0
G2                      0          0.0
G3                      0          0.0

=== UNIQUE VALUES PER COLUMN ===
            unique_count
school                 2
sex                    2
age                    8
address                2
famsize                2
Pstatus                2
Medu                   5
Fedu                   5
Mjob                   5
Fjob                   5
reason                 4
guardian               3
traveltime             4
studytime              4
failures               4
schoolsup              2
famsup                 2
paid                   2
activities             2
nursery                2
higher                 2
internet               2
romantic               2
famrel                 5
freetime               5
goout                  5
Dalc                   5
Walc                   5
health                 5
absences              34
G1                    17
G2                    17
G3                    18

=== CORRELATION BETWEEN NUMERIC COLUMNS ===
             age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  Dalc  Walc  health  absences    G1    G2    G3
age         1.00 -0.16 -0.16        0.07      -0.00      0.24    0.05      0.02   0.13  0.13  0.12   -0.06      0.18 -0.06 -0.14 -0.16
Medu       -0.16  1.00  0.62       -0.17       0.06     -0.24   -0.00      0.03   0.06  0.02 -0.05   -0.05      0.10  0.21  0.22  0.22
Fedu       -0.16  0.62  1.00       -0.16      -0.01     -0.25   -0.00     -0.01   0.04  0.00 -0.01    0.01      0.02  0.19  0.16  0.15
traveltime  0.07 -0.17 -0.16        1.00      -0.10      0.09   -0.02     -0.02   0.03  0.14  0.13    0.01     -0.01 -0.09 -0.15 -0.12
studytime  -0.00  0.06 -0.01       -0.10       1.00     -0.17    0.04     -0.14  -0.06 -0.20 -0.25   -0.08     -0.06  0.16  0.14  0.10
failures    0.24 -0.24 -0.25        0.09      -0.17      1.00   -0.04      0.09   0.12  0.14  0.14    0.07      0.06 -0.35 -0.36 -0.36
famrel      0.05 -0.00 -0.00       -0.02       0.04     -0.04    1.00      0.15   0.06 -0.08 -0.11    0.09     -0.04  0.02 -0.02  0.05
freetime    0.02  0.03 -0.01       -0.02      -0.14      0.09    0.15      1.00   0.29  0.21  0.15    0.08     -0.06  0.01 -0.01  0.01
goout       0.13  0.06  0.04        0.03      -0.06      0.12    0.06      0.29   1.00  0.27  0.42   -0.01      0.04 -0.15 -0.16 -0.13
Dalc        0.13  0.02  0.00        0.14      -0.20      0.14   -0.08      0.21   0.27  1.00  0.65    0.08      0.11 -0.09 -0.06 -0.05
Walc        0.12 -0.05 -0.01        0.13      -0.25      0.14   -0.11      0.15   0.42  0.65  1.00    0.09      0.14 -0.13 -0.08 -0.05
health     -0.06 -0.05  0.01        0.01      -0.08      0.07    0.09      0.08  -0.01  0.08  0.09    1.00     -0.03 -0.07 -0.10 -0.06
absences    0.18  0.10  0.02       -0.01      -0.06      0.06   -0.04     -0.06   0.04  0.11  0.14   -0.03      1.00 -0.03 -0.03  0.03
G1         -0.06  0.21  0.19       -0.09       0.16     -0.35    0.02      0.01  -0.15 -0.09 -0.13   -0.07     -0.03  1.00  0.85  0.80
G2         -0.14  0.22  0.16       -0.15       0.14     -0.36   -0.02     -0.01  -0.16 -0.06 -0.08   -0.10     -0.03  0.85  1.00  0.90
G3         -0.16  0.22  0.15       -0.12       0.10     -0.36    0.05      0.01  -0.13 -0.05 -0.05   -0.06      0.03  0.80  0.90  1.00

=== TOP 10 VALUES FOR CATEGORICAL COLUMNS ===

Column: school
school
GP    349
MS     46

Column: sex
sex
F    208
M    187

Column: address
address
U    307
R     88

Column: famsize
famsize
GT3    281
LE3    114

Column: Pstatus
Pstatus
T    354
A     41

Column: Mjob
Mjob
other       141
services    103
at_home      59
teacher      58
health       34

Column: Fjob
Fjob
other       217
services    111
teacher      29
at_home      20
health       18

Column: reason
reason
course        145
home          109
reputation    105
other          36

Column: guardian
guardian
mother    273
father     90
other      32

Column: schoolsup
schoolsup
no     344
yes     51

Column: famsup
famsup
yes    242
no     153

Column: paid
paid
no     214
yes    181

Column: activities
activities
yes    201
no     194

Column: nursery
nursery
yes    314
no      81

Column: higher
higher
yes    375
no      20

Column: internet
internet
yes    329
no      66

Column: romantic
romantic
no     263
yes    132

=== SIMPLE WARNING CHECKS ===
Possible ID-like columns: []
Constant columns: []
Duplicate rows: 0


TASK:


TASK

Review the dataset profile and identify:

1. Data quality issues.
2. Missing value concerns.
3. Duplicate record concerns.
4. Potential outlier concerns.
5. ID-like columns.
6. Constant or near-constant columns.
7. Redundant or highly correlated columns.
8. Potential target leakage or label leakage risks.
9. Data type issues.
10. Feature engineering opportunities.
11. Columns that may be candidates for removal before modelling.

For every issue provide:

- Issue
- Evidence from dataset profile
- Why it matters
- ML impact
- Recommended action
- Priority (High / Medium / Low)

Important:

- Do not recommend dropping a column solely because it appears in warning checks.
- Explain why before recommending removal.
- If evidence is insufficient, state:
  'Cannot be confirmed from dataset profile alone.'

Finally provide:

A. Data Quality Review
B. Recommended Actions
C. Suggested Cleaning Steps (in order)

Keep the answer concise but complete.

# **Step 8: Send Payload to Open AI & OpenAI recommendation Output/Response**

In [14]:
response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
    You are a professional data analyst writing a high-quality business analytics report.
    """,
    input=outcome
)

print(response.output_text)

## A. Data Quality Review

### 1) Data quality issues
**Issue:** No missing values detected
- **Evidence from dataset profile:** Missing values table shows **0 missing** for all 33 columns.
- **Why it matters:** Model imputation is unnecessary; however, other quality issues (e.g., invalid ranges) could still exist (not indicated here).
- **ML impact:** None from missingness; preprocessing can focus on validation/range checks.
- **Recommended action:** Run **range/category validity checks** for ordinal-like integer columns (cannot be confirmed from profile alone).
- **Priority:** Low

**Issue:** Potential invalid/atypical numeric magnitude for an ordinal-like feature
- **Evidence from dataset profile:** `absences` has **max = 75**, `G1/G2/G3` min–max are **0–19/20** range-like values, and many integer predictors have small discrete supports (e.g., `Dalc`, `Walc` min–max 1–5).
- **Why it matters:** If some columns are supposed to be ordinal (e.g., alcohol/health) or bounded (0/1/2/3/4), extreme values can distort tree splits.
- **ML impact:** Outliers may dominate impurity-based splits and reduce generalization.
- **Recommended action:** Verify whether `absences` is truly unbounded by design; if it’s intended to be capped/ordinal, cap or flag out-of-domain values.
- **Priority:** Medium

**Issue:** No duplicate rows detected
- **Evidence from dataset profile:** **Duplicate rows: 0**
- **Why it matters:** Reduced risk of inflated performance due to repeated records.
- **ML impact:** None.
- **Recommended action:** None beyond confirming duplicate definition (row-wise exact match).
- **Priority:** Low

---

### 2) Missing value concerns
**Issue:** Missingness not present, but data-type consistency still required
- **Evidence from dataset profile:** Missing counts are **0** for every column.
- **Why it matters:** Even without NaNs, categorical fields may contain unexpected strings (cannot be confirmed from profile alone).
- **ML impact:** Unexpected categories can cause training-time issues.
- **Recommended action:** Validate that categorical values match expected sets for each column (based on dataset documentation; not provided).
- **Priority:** Low

---

### 3) Duplicate record concerns
**Issue:** No exact duplicates
- **Evidence from dataset profile:** Duplicate rows: **0**
- **Why it matters:** Minimizes risk of leakage via repeated samples.
- **ML impact:** None.
- **Recommended action:** None.
- **Priority:** Low

---

### 4) Potential outlier concerns
**Issue:** Strong “evaluation target” variables are tightly related
- **Evidence from dataset profile:** Correlations among `G1`, `G2`, `G3` are very high:
  - `G1-G2` corr **0.85**, `G1-G3` **0.80**, `G2-G3` corr **0.90**
- **Why it matters:** If the target is one of these, including the others can create near-direct leakage.
- **ML impact:** Inflated performance; poor deployment behavior.
- **Recommended action:** Decide the intended target (not specified) and ensure **only the target** is used, excluding other `G*` columns if they would be known at prediction time.
- **Priority:** High

**Issue:** `absences` variability is large relative to most other numeric predictors
- **Evidence from dataset profile:** `absences` std **8.00**, max **75**, while many other integer features have small discrete ranges (e.g., `Dalc/Walc` max 5).
- **Why it matters:** May indicate heavy-tailed behavior.
- **ML impact:** Outliers can affect model calibration and split behavior.
- **Recommended action:** Flag extreme values (e.g., beyond typical quantiles) and confirm whether they are plausible.
- **Priority:** Medium

---

### 5) ID-like columns
**Issue:** No ID-like columns flagged
- **Evidence from dataset profile:** “Possible ID-like columns: []” and no column suggested as ID-like.
- **Why it matters:** If an ID exists but is not detected, it can cause memorization.
- **ML impact:** Could cause extreme overfitting.
- **Recommended action:** Cannot be confirmed from dataset profile alone. Still verify that none of the columns behave like identifiers (high uniqueness + no natural meaning).
- **Priority:** Low

---

### 6) Constant or near-constant columns
**Issue:** No constant columns detected
- **Evidence from dataset profile:** “Constant columns: []”
- **Why it matters:** No trivially uninformative features.
- **ML impact:** None.
- **Recommended action:** Low effort confirmation: check for very low-variance categories (not provided).
- **Priority:** Low

---

### 7) Redundant or highly correlated columns
**Issue:** High redundancy among grades
- **Evidence from dataset profile:** Very high correlations among `G1`, `G2`, `G3` (0.80–0.90).
- **Why it matters:** Multiple highly correlated predictors can be redundant and may amplify leakage risk depending on the target.
- **ML impact:** If not leakage, may still cause multicollinearity-like effects for linear models; for trees this is less harmful but can reduce interpretability.
- **Recommended action:** If leakage is not the concern (target selection independent), consider whether all `G*` are measured at the same time; otherwise exclude the ones not available.
- **Priority:** High (mainly due to potential leakage)

**Issue:** Multicollinearity between education level measures
- **Evidence from dataset profile:** `Medu` and `Fedu` correlation **0.62**.
- **Why it matters:** Redundant but usually not leakage.
- **ML impact:** Could be fine for tree models; interpretability may suffer.
- **Recommended action:** Keep for now; only remove after confirming modeling needs.
- **Priority:** Low

---

### 8) Potential target leakage or label leakage risks
**Issue:** Grade columns (`G1/G2/G3`) are highly correlated and likely temporally/causally linked
- **Evidence from dataset profile:** correlations: `G1-G2` 0.85, `G1-G3` 0.80, `G2-G3` 0.90; also `G1/G2/G3` have defined ranges (G1 min 3, max 19; G2 min 0 max 19; G3 min 0 max 20).
- **Why it matters:** If predicting `G3` (common in such datasets), using `G1` and `G2` is effectively using future/previous grades depending on the prediction setup.
- **ML impact:** Dramatically overoptimistic results and invalid deployment.
- **Recommended action:** Confirm the exact target definition/time of availability; exclude any grade variables not available at prediction time.
- **Priority:** High

---

### 9) Data type issues
**Issue:** Likely ordinal variables stored as integers without explicit ordinal mapping
- **Evidence from dataset profile:** Many numeric columns appear to be discrete ordinal scales (e.g., `Medu/Fedu` 0–4, `Dalc/Walc` 1–5, `famrel/freetime/goout/health` 1–5, `traveltime/studytime` 1–4).
- **Why it matters:** If some codes include invalid values (e.g., 0 where none expected), models may learn spurious patterns.
- **ML impact:** Mainly correctness of interpretation; tree models can still work but wrong assumptions can degrade performance.
- **Recommended action:** Validate that the observed min/max match expected codebooks for each ordinal field (dataset documentation not provided).
- **Priority:** Medium

**Issue:** Categorical variables stored as object
- **Evidence from dataset profile:** Many binary/low-cardinality predictors are `object` (e.g., `schoolsup`, `famsup`, `paid`, `higher`, `internet`, etc.).
- **Why it matters:** Ensures downstream pipelines treat them as categorical (one-hot/target encoding decisions).
- **ML impact:** Wrong handling (e.g., numerical coercion) could break learning.
- **Recommended action:** Confirm intended categorical handling method in the pipeline (not requested to implement).
- **Priority:** Low

---

### 10) Feature engineering opportunities
**Opportunity:** Temporal/grade aggregation features (only if target leakage is handled)
- **Evidence from dataset profile:** `G1`, `G2`, `G3` exist and are highly correlated.
- **Why it matters:** If predicting a non-grade target, engineered interactions among grade history might help. If predicting `G3`, use only permitted history.
- **ML impact:** Potentially improved performance.
- **Recommended action:** Only after confirming target/time constraints.
- **Priority:** Medium

**Opportunity:** Drinking/behavior intensity summaries
- **Evidence from dataset profile:** `Dalc` and `Walc` plus related behavior variables like `goout`, `health`.
- **Why it matters:** Combined features may capture overall consumption/behavior intensity.
- **ML impact:** Might improve generalization.
- **Recommended action:** Consider creating derived variables only after ensuring no leakage.
- **Priority:** Low

---

### 11) Columns that may be candidates for removal before modelling
*(Do not drop solely due to warning checks; removal depends on target/time availability and validity.)*

**Candidate:** One or more of `G1`, `G2`
- **Evidence from dataset profile:** `G1/G2/G3` very highly correlated (0.80–0.90).
- **Why it matters:** High likelihood of label leakage depending on target definition.
- **ML impact:** Excluding them can prevent inflated performance.
- **Recommended action:** Exclude any grade features not available at prediction time; at minimum, avoid using other grade columns if predicting one of them.
- **Priority:** High

**Candidate:** None else can be confirmed from dataset profile alone
- **Evidence from dataset profile:** No missingness; no constant columns; no ID-like columns flagged; no invalid category evidence provided.
- **Why it matters:** Dropping without evidence risks loss of signal.
- **ML impact:** Unnecessary feature loss.
- **Recommended action:** Keep remaining features until you confirm (via dataset description) whether any are unavailable at prediction time or have invalid codes.
- **Priority:** Low

---

## B. Recommended Actions (prioritized)
1. **Leakage check (High):** Confirm the intended target and remove/exclude `G*` predictors that would not be available at inference time.
2. **Outlier/range validation (Medium):** Validate codebooks for discrete integer/ordinal features; review `absences` extremes (max 75).
3. **Type/validity validation (Medium/Low):** Ensure object categorical fields contain only expected categories.
4. **Keep correlated features unless leakage is present (Low/Medium):** `G1/G2/G3` redundancy is expected; `Medu/Fedu` correlation is likely benign.

---

## C. Suggested Cleaning Steps (in order)
1. **Define/confirm target + availability** (external to profile, but required): decide whether `G1`, `G2`, `G3` are permissible inputs when predicting the chosen target.
2. **Schema validation:** check each ordinal-like integer column (`Medu`, `Fedu`, `traveltime`, `studytime`, `failures`, `famrel`, `freetime`, `goout`, `Dalc`, `Walc`, `health`) matches expected min/max code ranges (profile shows plausible but confirm).
3. **Outlier flagging:** inspect `absences` distribution and flag extreme values for confirmation (max 75).
4. **Categorical validity:** verify categorical object columns only contain known categories (profile shows observed top values, but completeness/unknown tokens can’t be confirmed).
5. **No missing-value handling needed:** since missingness is 0 across all columns, skip imputation steps.

If you tell me which column is the target (and whether prediction happens before/after `G1/G2` are known), I can refine the leakage recommendations specifically to that setup.

# **Template combine  step 5-8 (Create context + Instruction + Final Payload + send to Open AI & with Open AI recommendation output/Response)**

In [31]:
# Prompt : Target Known
# eg. target_column = "Price"

context = """
You are an expert data scientist with extensive knowledge of tree-based models.

Always justify recommendations using evidence from the dataset profile.

You are reviewing a dataset before machine learning modelling.

The goal is to identify data quality issues and provide preprocessing recommendations.

The target variable has been specified in the dataset profile.

Focus on identifying issues that may impact predictive modelling performance.

Do not perform encoding, scaling, feature selection, train/test splitting, or modelling.

Focus only on data quality assessment and data cleaning.
"""

instruction = """
Review the dataset profile and identify:

1. Data quality issues that should be resolved before modelling.
2. Missing value concerns.
3. Duplicate record concerns.
4. Potential outlier concerns.
5. ID-like columns.
6. Constant or near-constant columns.
7. Highly correlated or potentially redundant columns.
8. Potential target leakage issues.
9. Potential label leakage issues.
10. Feature engineering opportunities.
11. Columns that should be removed before modelling.

For each issue provide:

- Explanation
- Evidence from dataset profile
- ML impact
- Recommendation
- Priority (High / Medium / Low)

Important:

- Assess potential leakage only when supported by evidence from the dataset profile.
- Do NOT recommend dropping a column solely because it appears in warning checks.
- If evidence is insufficient, state:
  'Cannot be confirmed from dataset profile alone.'
- Do not speculate.

Then generate Python code to handle the identified issues.

Requirements:

1. Create one helper function for each issue identified.
2. Create a wrapper function that calls these helper functions using True/False parameters.
3. Provide a single-line example showing how to run the wrapper function.
4. Do NOT perform encoding, scaling, feature selection, or modelling.
5. Focus only on data cleaning and preparation.

Output format:

A. Data Quality Review
B. Recommended Actions
C. Python Cleaning Functions
D. Wrapper Function
E. Example Usage
"""

outcome = f"""
CONTEXT:
{context}

DATASET INFORMATION:
{payload_text}

TASK:
{instruction}
"""

response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
You are a professional data analyst writing a high-quality business analytics report.
""",
    input=outcome
)

print(response.output_text)

## A. Data Quality Review

> Note: The dataset profile does **not specify the target column**, so leakage checks related to the specific label cannot be fully confirmed.

### 1) Missing value concerns
- **Explanation**: No missing values reported in any column.
- **Evidence from dataset profile**: “MISSING VALUES: … 0 missing_count 0.0 missing_pct” for all 33 columns.
- **ML impact**: Likely minimal for imputation, but other data-quality issues (invalid values, outliers) can still exist.
- **Recommendation**: No imputation required based on the provided profile. Still validate for “hidden” missingness (e.g., empty strings in categoricals) and numeric sentinel values.
- **Priority**: Low

### 2) Duplicate record concerns
- **Explanation**: No duplicates reported.
- **Evidence**: “DUPLICATE ROWS: 0”
- **ML impact**: Minimal.
- **Recommendation**: Still consider near-duplicates only if business rules suggest them (not evidenced here).
- **Priority**: Low

### 3) Potential outlier concerns (numeric)
- **Explanation**: Some numeric variables show ranges that are much wider than typical Likert-style scales, suggesting possible encoding/sanity issues or true outliers.
- **Evidence from dataset profile**:
  - `absences`: min **0**, max **75**, mean **5.709**, std **8.003** → heavy-tailed count-like behavior.
  - `G1`: min **3**, max **19**; `G2`: min **0**, max **19**; `G3`: min **0**, max **20** → partially inconsistent lower bounds (e.g., `G1` min 3 but `G2/G3` min 0).
  - All other numeric features largely fall into small integer ranges (1–5), suggesting `absences` and grade columns need careful verification.
- **ML impact**: Tree models are robust, but extreme values can still distort split thresholds, especially with small n=395. Invalid ranges can also cause systematic bias.
- **Recommendation**:
  - Validate **allowed ranges** for each numeric feature (especially `absences`, `G1`, `G2`, `G3`) against the dataset’s known scale definition.
  - For `absences`, consider winsorization/capping if confirmed to be mostly noise/outliers (only after range validation).
- **Priority**: Medium

### 4) ID-like columns
- **Explanation**: No obvious ID field present.
- **Evidence**: “Potential ID COLUMNS: []”
- **ML impact**: Low.
- **Recommendation**: Keep as-is unless additional profile indicates identifiers (not shown).
- **Priority**: Low

### 5) Constant or near-constant columns
- **Explanation**: No constant columns; still check for near-constant categoricals in case one value dominates heavily.
- **Evidence**:
  - “CONSTANT COLUMNS: []”
  - For categoricals: `higher=yes` dominates (freq 375/395), `internet=yes` (329/395), `nursery=yes` (314/395)
- **ML impact**: Near-constant features can reduce split usefulness and add noise; for tree ensembles it’s usually minor but can waste capacity and increase variance.
- **Recommendation**:
  - Keep them unless they are truly uninformative; optionally log-validate their variance / dominance.
  - Confirm whether “yes/no” features are properly coded (no hidden categories).
- **Priority**: Low

### 6) Highly correlated / potentially redundant columns (numeric)
- **Explanation**: Several grade variables are extremely correlated, indicating redundancy (not necessarily a problem for trees, but it affects interpretability and can inflate importance).
- **Evidence from correlation matrix**:
  - `G1` vs `G2`: **0.852**
  - `G1` vs `G3`: **0.801**
  - `G2` vs `G3`: **0.905**
- **ML impact**: Redundancy can cause unstable feature importance and collinearity-driven artifacts (especially when the target is one of these grades).
- **Recommendation**:
  - If the target is **G1/G2/G3**, leakage/target issues arise (see leakage sections below).
  - Otherwise, consider removing redundant grade predictors *only if confirmed by the target definition*; cannot be confirmed from the dataset profile alone.
- **Priority**: Medium

### 7) Target leakage issues (cannot be confirmed fully)
- **Explanation**: If the target column is one of `G1`, `G2`, or `G3`, then including other grade columns (and possibly `absences`/study behavior correlated with grades) may create leakage-like behavior depending on how the target is defined.
- **Evidence**:
  - Correlation among `G1/G2/G3` is very high (0.80–0.91).
  - **Target column not specified** in the profile → cannot confirm.
- **ML impact**: Severe if target is a grade and you include its correlated counterparts; the model may essentially “copy” the label.
- **Recommendation**:
  - **Cannot be confirmed from dataset profile alone.**
  - Once the target is known, drop or avoid using the other grade(s) if they represent the “same-time” measurement used to define the target.
- **Priority**: High (conditional on target choice)

### 8) Label leakage issues
- **Explanation**: Some fields look like post-outcome indicators (e.g., final grades) but again target is unknown.
- **Evidence**: `G1/G2/G3` appear to be exam scores.
- **ML impact**: Potentially high if these are used improperly relative to target.
- **Recommendation**:
  - **Cannot be confirmed from dataset profile alone.**
- **Priority**: Medium/High (conditional)

### 9) Feature engineering opportunities (data-quality-driven)
- **Explanation**: With tree models, raw integers and ordinal categories can work well, but some derived features can help handle known structure and outlier counts.
- **Evidence**:
  - `traveltime`, `studytime`, `failures`, `Dalc`, `Walc`, `health` have small integer ranges typical of ordinal scales.
  - `absences` is count-like with wide range.
- **ML impact**: Feature transformations can improve robustness to outliers and nonlinearity.
- **Recommendation** (cleaning-safe):
  - Cap extreme `absences` after confirming range validity; optionally create `absences_log1p` (does not require scaling/encoding).
  - Convert “no/yes” categoricals to consistent case/trim (string hygiene).
- **Priority**: Low/Medium

### 10) Columns that should be removed before modelling
- **Explanation**: No column is confirmed to be invalid or purely ID-like from the profile alone.
- **Evidence**:
  - No constants; no missing; no duplicates; no ID columns detected.
- **ML impact**: Removing without evidence can harm performance.
- **Recommendation**:
  - **Cannot be confirmed from dataset profile alone.**
  - Conditional removal only after target is specified (e.g., avoid redundant grade columns if they constitute leakage).
- **Priority**: Medium (conditional)

---

## B. Recommended Actions (prioritized list)

1) **Validate grade and absence ranges (outlier/sanity checks)**
- **Why**: `absences` max=75 with large std; grade minimums differ (`G1 min 3` vs `G2/G3 min 0`), suggesting possible coding inconsistencies.
- **Priority**: Medium

2) **String hygiene for categoricals** (trim whitespace, normalize casing, check unexpected categories)
- **Why**: Categorical columns contain values like `yes/no`, job categories, etc. Even with 0 missing, empty strings or inconsistent capitalization can exist but won’t appear as NaNs.
- **Priority**: Medium

3) **Post-target check for leakage among `G1/G2/G3`** (once target is known)
- **Why**: Extremely high correlations among `G1/G2/G3` (0.80–0.91). If target is one of them, using the others is likely label leakage.
- **Priority**: High (conditional on target)

4) **Optional redundancy handling for grade columns** (once target is known / if leakage not present)
- **Why**: Grade redundancy can cause unstable importance; tree models may not need it, but it can help interpretability and may reduce variance.
- **Priority**: Medium (conditional)

5) **No action** for missing values and duplicates (based on profile)
- **Priority**: Low

---

## C. Python Cleaning Functions

```python
import pandas as pd
import numpy as np

# -----------------------------
# Helper 1: Sanity-check & clean numeric ranges / outliers
# -----------------------------
def clean_numeric_range_and_outliers(df, numeric_cols=None,
                                      absences_col="absences",
                                      grades_cols=("G1", "G2", "G3"),
                                      cap_absences_quantile=0.995,
                                      do_cap_absences=True):
    """
    - Validates numeric columns are truly numeric and within plausible bounds.
    - For absences: optionally cap extreme values using a high quantile (robustness).
    """
    df = df.copy()
    if numeric_cols is None:
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()

    # Coerce to numeric safely (does not encode categoricals)
    for c in numeric_cols:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    # Absences sanity
    if absences_col in df.columns:
        # If negatives exist, set to NaN (or cap to 0) since absences should not be negative
        neg_mask = df[absences_col] < 0
        if neg_mask.any():
            df.loc[neg_mask, absences_col] = np.nan

        if do_cap_absences:
            # Cap high tail to reduce extreme leverage
            q = df[absences_col].quantile(cap_absences_quantile)
            if pd.notna(q):
                df[absences_col] = np.where(df[absences_col] > q, q, df[absences_col])

    # Grade sanity checks (bounds are dataset-profile-driven only; adjust if your spec differs)
    for g in grades_cols:
        if g in df.columns:
            # If grades are expected within [0,20] or [0,19] but profile shows max 20.
            # We do conservative clipping to [0, 20].
            df[g] = np.where(df[g].notna(), df[g], df[g])
            df[g] = df[g].clip(lower=0, upper=20)

    return df


# -----------------------------
# Helper 2: Categorical string hygiene
# -----------------------------
def clean_categorical_string_hygiene(df, categorical_cols=None):
    """
    - Trims whitespace, normalizes casing for categorical columns.
    - Converts empty strings to NaN (optional; here we set to NaN for later handling).
    """
    df = df.copy()
    if categorical_cols is None:
        categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

    for c in categorical_cols:
        df[c] = df[c].astype("object")
        # Convert empty/whitespace-only to NaN
        df[c] = df[c].replace(r'^\s*$', np.nan, regex=True)
        # Trim
        df[c] = df[c].astype(str).str.strip()
        # Normalize common binary values to lower-case for consistency
        df[c] = df[c].str.lower()

        # If we created "nan" string, revert to real NaN
        df[c] = df[c].replace("nan", np.nan)

    return df


# -----------------------------
# Helper 3: Validate and mark unexpected categories (report-style cleaning)
# -----------------------------
def flag_unexpected_categories(df, expected_categories=None, categorical_cols=None):
    """
    - Optionally checks if categories fall within an expected set per column.
    - This is data-quality 'cleaning' via validation; does not drop rows by default.
    expected_categories: dict {col: set/list of allowed categories}
    Returns df with additional boolean columns: f"invalid_{col}" when expected provided.
    """
    df = df.copy()
    if categorical_cols is None:
        categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

    expected_categories = expected_categories or {}

    for col in categorical_cols:
        if col in expected_categories:
            allowed = set(expected_categories[col])
            df[f"invalid_{col}"] = df[col].notna() & (~df[col].isin(allowed))

    return df


# -----------------------------
# Helper 4: Conditional grade-column leakage prevention scaffold (target-known)
# -----------------------------
def drop_potential_grade_leakage_columns(df, target_col, grade_cols=("G1","G2","G3"), drop_if_target_in_grades=True):
    """
    If the target is one of the grade columns, drop the other grade columns to reduce label leakage risk.
    - This requires target_col to be provided.
    - Does NOT assume target definition beyond its name.
    """
    df = df.copy()
    if not drop_if_target_in_grades:
        return df

    if target_col in grade_cols:
        other = [c for c in grade_cols if c != target_col and c in df.columns]
        df = df.drop(columns=other, errors="ignore")
    return df
```

---

## D. Wrapper Function

```python
def preprocess_cleaning_wrapper(
    df,
    target_col=None,
    do_clean_numeric=True,
    do_clean_cat_strings=True,
    do_flag_unexpected_cats=False,
    expected_categories=None,
    do_drop_grade_leakage_if_target_is_grade=True
):
    """
    Cleans dataset for data quality; does not encode, scale, feature select, or split.
    """
    out = df.copy()

    if do_clean_numeric:
        out = clean_numeric_range_and_outliers(out)

    if do_clean_cat_strings:
        out = clean_categorical_string_hygiene(out)

    if do_flag_unexpected_cats and expected_categories:
        out = flag_unexpected_categories(out, expected_categories=expected_categories)

    if target_col is not None:
        out = drop_potential_grade_leakage_columns(
            out,
            target_col=target_col,
            drop_if_target_in_grades=do_drop_grade_leakage_if_target_is_grade
        )
    else:
        # Leakage prevention cannot be applied because target is unknown.
        # This wrapper leaves grades unchanged.
        pass

    return out
```

---

## E. Example Usage (single line)

```python
df_clean = preprocess_cleaning_wrapper(df, target_col="G3", do_flag_unexpected_cats=False)
```

In [30]:
# Prompt : Target Unknown
# target_column = None

context = """
You are an expert data scientist with extensive knowledge of tree-based models.

Always justify recommendations using evidence from the dataset profile.

You are reviewing a dataset before machine learning modelling.

The goal is to identify data quality issues and provide preprocessing recommendations.

The target variable has NOT been specified.

Do not assume a target variable.

Do not assess target leakage or label leakage because the target is unknown.

Focus only on data quality assessment, exploratory review, and data cleaning preparation.

Do not perform encoding, scaling, feature selection, train/test splitting, or modelling.
"""

instruction = """
Review the dataset profile and identify:

1. Data quality issues that should be resolved before modelling.
2. Missing value concerns.
3. Duplicate record concerns.
4. Potential outlier concerns.
5. ID-like columns.
6. Constant or near-constant columns.
7. Highly correlated or potentially redundant columns.
8. Data type issues.
9. Possible target column candidates (if obvious).
10. Feature engineering opportunities.
11. Columns that may require further investigation before modelling.

For each issue provide:

- Explanation
- Evidence from dataset profile
- ML impact
- Recommendation
- Priority (High / Medium / Low)

Important:

- Do NOT assume a target variable.
- Do NOT assess target leakage.
- Do NOT recommend dropping a column solely because it appears in warning checks.
- If evidence is insufficient, state:
  'Cannot be confirmed from dataset profile alone.'
- Do not speculate.

Then generate Python code to handle the identified issues.

Requirements:

1. Create one helper function for each issue identified.
2. Create a wrapper function that calls these helper functions using True/False parameters.
3. Provide a single-line example showing how to run the wrapper function.
4. Do NOT perform encoding, scaling, feature selection, or modelling.
5. Focus only on data cleaning and preparation.

Output format:

A. Data Quality Review
B. Recommended Actions
C. Python Cleaning Functions
D. Wrapper Function
E. Example Usage
"""

outcome = f"""
CONTEXT:
{context}

DATASET INFORMATION:
{payload_text}

TASK:
{instruction}
"""

response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
You are a professional data analyst writing a high-quality business analytics report.
""",
    input=outcome
)

print(response.output_text)

## A. Data Quality Review

> Dataset: 395 rows × 33 columns, no duplicate rows, no missing values reported in the profile.

### 1) Data quality issues that should be resolved before modelling

**Issue 1.1 — Unexpected numeric ranges/outliers (notably `absences`, `G2/G3`, and grades)**
- **Explanation:** Several numeric columns have ranges that may be inconsistent with expected ordinal scales. This dataset appears to contain integer-coded survey/academic features and grades. The presence of a large `absences` maximum (75) and grade maxima up to 20 suggest outliers or encoding/scale inconsistencies that should be validated.
- **Evidence from dataset profile:**
  - `absences`: min 0, **max 75**, mean 5.709 (high spread; std 8.003)
  - `G1`: min 3, max 19; `G2`: min 0, max 19; `G3`: min 0, max 20
  - Correlations among `G1/G2/G3` are very high (0.801–0.905), suggesting redundancy but also indicating grades likely share a common scale.
- **ML impact:** Tree models are robust to outliers, but extreme or mis-scaled values can cause unstable splits and degrade generalization, especially if the numeric coding is wrong (e.g., grades treated as continuous when they should be categorical/ordinal).
- **Recommendation (validate/clean):**
  - Verify the **expected domain** for `absences` and grade columns with the dataset source documentation.
  - If domain violations exist (values outside allowed ranges), correct or set them to missing for imputation.
  - If values are valid, consider **outlier diagnostics** (winsorization/capping) as an optional preprocessing step (do not drop rows).
- **Priority:** **High**

---

**Issue 1.2 — Possible categorical “binary” columns stored as `object`**
- **Explanation:** Many categorical columns have `unique_count=2` and represent binary states (e.g., `schoolsup`, `famsup`, `paid`, `higher`, `internet`, `romantic`, `sex`, `address`, `Pstatus`, etc.). If their values aren’t strictly standardized (e.g., “yes/no”, “t/f”, “True/False”), model training can be inconsistent.
- **Evidence from dataset profile:**
  - Several object columns have exactly 2 unique values:
    - `schoolsup`: yes/no (top: no=344, yes=51)
    - `famsup`: yes/no (yes=242, no=153)
    - `paid`: yes/no (no=214, yes=181)
    - `higher`: yes/no (yes=375, no=20)
    - `internet`: yes/no (yes=329, no=66)
    - `romantic`: no/yes (no=263, yes=132)
  - Also `address`: U/R (top U=307)
  - `Pstatus`: T/A (top T=354)
- **ML impact:** Inconsistent string formatting (case/spaces/alternate tokens) can lead to unintended categories and poor splits.
- **Recommendation:**
  - Standardize categorical tokens: trim whitespace, unify casing.
  - Validate all unique values per categorical column against an allowed vocabulary; flag unexpected categories.
- **Priority:** **Medium**

---

**Issue 1.3 — Column type and semantic consistency checks for ordinal/integer-coded categories**
- **Explanation:** Several integer columns look like they are ordinal-coded survey/assessment results (e.g., `Medu`, `Fedu`, `traveltime`, `studytime`, `failures`, `health`, `famrel`, `freetime`, `goout`, `Dalc`, `Walc`). These should be checked for being within expected ordinal bounds (commonly 0–4 or 1–5 depending on encoding).
- **Evidence from dataset profile:**
  - `Medu`/`Fedu`: min 0 max 4 (good), but confirm meaning of 0
  - `traveltime`: min 1 max 4
  - `studytime`: min 1 max 4
  - `failures`: min 0 max 3
  - `health`: min 1 max 5
  - `famrel`/`freetime`/`goout`/`Dalc`/`Walc`: min 1 max 5
- **ML impact:** If any ordinal columns contain invalid codes, tree splits may model noise; also if codes are actually nominal, ordinal assumptions in interpretation are wrong (trees won’t assume order explicitly, but order affects your feature engineering decisions).
- **Recommendation:**
  - Validate each ordinal-coded integer column against allowed ranges.
  - If invalid codes exist, set them to missing and impute or cap (based on downstream plan).
- **Priority:** **Medium**

---

### 2) Missing value concerns
- **Explanation:** The profile reports **0 missing values in all columns**.
- **Evidence from dataset profile:** Missing count = 0 and missing_pct = 0.0 for every column listed.
- **ML impact:** Minimal missingness risk.
- **Recommendation:** Still perform a quick “data-level” check for:
  - hidden missing tokens like `' ?'`, `'NA'`, `' '` in object columns (not captured in the current profile).
  - numeric columns that might have been parsed from strings with coercion issues.
- **Priority:** **Low**

---

### 3) Duplicate record concerns
- **Explanation:** Duplicate rows count is 0.
- **Evidence from dataset profile:** Duplicate Rows: 0
- **ML impact:** Low.
- **Recommendation:** Optionally check for near-duplicates (same features after normalization) only if you suspect whitespace/casing issues in categorical columns.
- **Priority:** **Low**

---

### 4) Potential outlier concerns
- **Explanation:** Outliers likely exist in `absences` and possibly in grade columns (`G1/G2/G3`), as indicated by wide ranges and small `G1` min (3) alongside `G2/G3` min 0.
- **Evidence from dataset profile:**
  - `absences` max 75 (std 8.003 vs mean 5.709)
  - `G1`: min 3, max 19; `G2`: min 0; `G3`: min 0
- **ML impact:** Outliers can dominate impurity reductions for trees (especially if outliers form small “pure” partitions).
- **Recommendation:**
  - Use robust diagnostics (IQR/Z-score) to **flag** extreme points.
  - Prefer capping/winsorization only after verifying that these values are valid according to data source definitions.
- **Priority:** **High** (because `absences` is clearly high relative to typical mean)

---

### 5) ID-like columns
- **Explanation:** No explicit ID columns are flagged.
- **Evidence from dataset profile:** “Potential ID Columns: []”
- **ML impact:** Low.
- **Recommendation:** Still verify no column has near-unique values per row (not possible to confirm from provided profile alone).
- **Priority:** **Low**

---

### 6) Constant or near-constant columns
- **Explanation:** No constant columns detected.
- **Evidence from dataset profile:** Constant columns: []
- **ML impact:** None.
- **Recommendation:** Check near-constant for categorical columns with extremely dominant category (e.g., `higher` yes=375/395), which may still be predictive but can reduce variance.
- **Priority:** **Low**

---

### 7) Highly correlated or potentially redundant columns
- **Explanation:** `G1`, `G2`, `G3` are extremely correlated, indicating redundancy. This is not necessarily bad (trees can handle it), but it can inflate importance and complicate interpretation. It also suggests that if grades represent the same construct, you may choose to keep only one later—but the current task is only pre-modelling preparation.
- **Evidence from dataset profile:**
  - Corr(`G1`,`G2`)=0.852
  - Corr(`G1`,`G3`)=0.801
  - Corr(`G2`,`G3`)=0.905
- **ML impact:** Potential multicollinearity effects on interpretation; some algorithms are affected, but tree-based models generally handle correlated features. Still, redundancy can waste capacity and create unstable feature importance.
- **Recommendation:**
  - Flag these columns for downstream review (e.g., consider aggregating or keeping a single target-representative later). **Do not drop yet** without target-specific reasoning.
- **Priority:** **Medium**

---

### 8) Data type issues
- **Explanation:** All columns have plausible types (objects for categories, int64 for numeric). However, object columns may include numeric-like strings; and integer columns should be checked for invalid categories (e.g., zeros in ordinal columns where zero might be “missing”).
- **Evidence from dataset profile:**
  - Numeric columns are `int64` throughout for: `age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3`
  - Object columns are categorical (e.g., `school`, `sex`, `address`, etc.).
- **ML impact:** If some object columns actually represent ordinal integers stored as strings, modeling will treat them as categorical and could reduce performance.
- **Recommendation:** For object columns, confirm the unique values are only categorical tokens; for integer columns, confirm all are within expected domains.
- **Priority:** **Medium**

---

### 9) Possible target column candidates (if obvious)
- **Explanation:** Cannot assess because **target is not specified** and there is no explicit target column name in the profile.
- **Evidence from dataset profile:** No “Target column” provided.
- **ML impact:** N/A.
- **Recommendation:** **Cannot be confirmed from dataset profile alone.**
- **Priority:** **Low**

---

### 10) Feature engineering opportunities
- **Explanation:** Only general opportunities (no modelling):
  - Aggregate related grade features: `G1/G2/G3` could be combined (e.g., mean or trend) after validation.
  - Create composite “alcohol use” indices from `Dalc/Walc` (only after verifying coding).
  - Use attendance/routine signals: `absences` may pair with `studytime` and `failures`.
- **Evidence from dataset profile:**
  - Strong correlation among grades suggests derived features could help stabilize representations.
  - `Dalc` and `Walc` are moderately correlated (corr=0.648) suggesting a combined measure.
- **ML impact:** Can improve model interpretability and reduce redundancy.
- **Recommendation:** Add candidate engineered features later; validate ranges first.
- **Priority:** **Low** (pre-modelling stage)

---

### 11) Columns that may require further investigation before modelling
- **Explanation:** Domain validation is required for:
  - `absences` (large max)
  - grade columns min/max patterns (`G1` min 3 while others min 0)
  - ordinal integer columns where 0 may represent “no education” or missingness depending on encoding.
- **Evidence from dataset profile:**
  - `absences` max 75
  - `G1` min 3 vs `G2/G3` min 0
  - `failures` min 0 and max 3
  - `Medu/Fedu` min 0 and max 4
- **ML impact:** If invalid codes exist, trees will learn incorrect thresholds.
- **Recommendation:** Perform rule-based validation and flag violations.
- **Priority:** **High**

---

## B. Recommended Actions (prioritized)

1. **Validate numeric domains and flag/correct out-of-range values**
   - Focus: `absences`, `G1/G2/G3`, and ordinal-coded integer columns.
   - **Priority: High**.

2. **Standardize categorical string tokens** (trim, casefold, unify common “yes/no” variants)
   - **Priority: Medium**.

3. **Re-check hidden missing tokens and coercion artifacts in object columns**
   - Despite “no missing values” in the profile, confirm that tokens like `'?'`, `'NA'`, empty strings aren’t present.
   - **Priority: Low**.

4. **Flag redundant grade features for downstream consideration**
   - Don’t drop yet; just annotate for later decisions.
   - **Priority: Medium**.

---

## C. Python Cleaning Functions

```python
import numpy as np
import pandas as pd

def _identify_object_columns(df: pd.DataFrame):
    return [c for c in df.columns if df[c].dtype == "object"]

def check_and_flag_numeric_domain_issues(
    df: pd.DataFrame,
    numeric_domain_rules: dict,
    set_invalid_to_na: bool = False,
    na_sentinel: str = "NA_INVALID"
):
    """
    numeric_domain_rules: dict like:
      {
        "absences": {"min": 0, "max": 75},
        "G1": {"min": 0, "max": 20},
        ...
      }
    """
    out = df.copy()
    flags = []

    for col, rule in numeric_domain_rules.items():
        if col not in out.columns:
            continue

        if not pd.api.types.is_numeric_dtype(out[col]):
            # Domain check cannot be applied reliably if not numeric
            continue

        col_min = rule.get("min", None)
        col_max = rule.get("max", None)

        mask = pd.Series(False, index=out.index)
        if col_min is not None:
            mask = mask | (out[col] < col_min)
        if col_max is not None:
            mask = mask | (out[col] > col_max)

        n_bad = int(mask.sum())
        if n_bad > 0:
            flags.append({"issue": f"numeric_domain_violation:{col}", "n_invalid": n_bad})

            if set_invalid_to_na:
                out.loc[mask, col] = np.nan

    return out, pd.DataFrame(flags)

def cap_numeric_outliers_iqr(
    df: pd.DataFrame,
    columns: list,
    k: float = 1.5,
    set_outliers_to_cap: bool = True
):
    """
    Caps values outside [Q1 - k*IQR, Q3 + k*IQR] per column.
    If set_outliers_to_cap=False, just flags by adding a boolean mask columns.
    """
    out = df.copy()
    flags = []

    for col in columns:
        if col not in out.columns:
            continue
        if not pd.api.types.is_numeric_dtype(out[col]):
            continue

        x = out[col]
        q1 = x.quantile(0.25)
        q3 = x.quantile(0.75)
        iqr = q3 - q1
        if iqr == 0:
            continue

        lo = q1 - k * iqr
        hi = q3 + k * iqr
        mask = (x < lo) | (x > hi)
        n_out = int(mask.sum())

        if n_out > 0:
            flags.append({"issue": f"iqr_outliers:{col}", "n_outliers": n_out, "lo": lo, "hi": hi})
            if set_outliers_to_cap:
                out.loc[x < lo, col] = lo
                out.loc[x > hi, col] = hi

    return out, pd.DataFrame(flags)

def standardize_categorical_strings(
    df: pd.DataFrame,
    lowercase: bool = False,
    strip_whitespace: bool = True,
    replacements: dict = None
):
    """
    Standardizes object columns by trimming/normalizing whitespace and casing.
    replacements: dict mapping specific tokens to canonical ones, e.g.
      {" yes": "yes", "Yes": "yes", " NO": "no", "No": "no"}
    """
    out = df.copy()
    obj_cols = _identify_object_columns(out)

    if replacements is None:
        replacements = {}

    for col in obj_cols:
        s = out[col].astype("string")

        if strip_whitespace:
            s = s.str.strip()

        # Apply explicit replacements first
        if replacements:
            s = s.replace(replacements)

        if lowercase:
            s = s.str.lower()

        out[col] = s.astype("object")

    return out

def detect_hidden_missing_tokens_in_objects(
    df: pd.DataFrame,
    missing_tokens: list = None
):
    """
    Checks object columns for common hidden missing tokens.
    """
    if missing_tokens is None:
        missing_tokens = ["?", "NA", "N/A", "na", "null", "None", "", "   "]

    out = df.copy()
    obj_cols = _identify_object_columns(out)
    flags = []

    token_set = set(missing_tokens)

    for col in obj_cols:
        s = out[col].astype("string").str.strip()
        mask = s.isin(token_set) | s.eq("nan")
        n = int(mask.sum())
        if n > 0:
            flags.append({"issue": f"hidden_missing_tokens:{col}", "n_rows": n})

    return out, pd.DataFrame(flags)

def report_redundant_correlated_features(
    df: pd.DataFrame,
    cols: list,
    threshold: float = 0.85
):
    """
    Computes correlation matrix among numeric columns and flags pairs > threshold (abs).
    """
    num_df = df.copy()
    present = [c for c in cols if c in num_df.columns and pd.api.types.is_numeric_dtype(num_df[c])]
    if len(present) < 2:
        return df, pd.DataFrame([])

    corr = num_df[present].corr(numeric_only=True)
    pairs = []
    for i in range(len(present)):
        for j in range(i+1, len(present)):
            c1, c2 = present[i], present[j]
            v = corr.loc[c1, c2]
            if np.isfinite(v) and abs(v) >= threshold:
                pairs.append({"pair": f"{c1}__{c2}", "abs_corr": float(abs(v)), "corr": float(v)})

    return df, pd.DataFrame(pairs)
```

---

## D. Wrapper Function

```python
def clean_prepare_dataset(
    df: pd.DataFrame,
    do_numeric_domain_checks: bool = True,
    do_iqr_outlier_capping: bool = True,
    do_categorical_standardization: bool = True,
    do_hidden_missing_token_check: bool = True,
    do_redundancy_correlation_report: bool = True,
    numeric_domain_rules: dict = None,
    iqr_columns: list = None,
    cap_k: float = 1.5,
    categorical_lowercase: bool = False,
    categorical_replacements: dict = None,
    hidden_missing_tokens: list = None,
    redundant_grade_cols: list = None,
    corr_threshold: float = 0.85,
    set_invalid_to_na: bool = False
):
    """
    Returns:
      cleaned_df, diagnostics_dict
    """
    diagnostics = {}

    out = df.copy()

    # 1) Numeric domain checks
    if do_numeric_domain_checks:
        if numeric_domain_rules is None:
            numeric_domain_rules = {
                # Conservative defaults based on common grade/attendance encoding;
                # adjust after checking dataset documentation.
                "absences": {"min": 0, "max": 75},
                "G1": {"min": 0, "max": 20},
                "G2": {"min": 0, "max": 20},
                "G3": {"min": 0, "max": 20},

                "age": {"min": 10, "max": 100},  # broad safety check
                "Medu": {"min": 0, "max": 4},
                "Fedu": {"min": 0, "max": 4},
                "traveltime": {"min": 1, "max": 4},
                "studytime": {"min": 1, "max": 4},
                "failures": {"min": 0, "max": 3},
                "famrel": {"min": 1, "max": 5},
                "freetime": {"min": 1, "max": 5},
                "goout": {"min": 1, "max": 5},
                "Dalc": {"min": 1, "max": 5},
                "Walc": {"min": 1, "max": 5},
                "health": {"min": 1, "max": 5},
            }
        out, diag = check_and_flag_numeric_domain_issues(
            out,
            numeric_domain_rules=numeric_domain_rules,
            set_invalid_to_na=set_invalid_to_na
        )
        diagnostics["numeric_domain"] = diag

    # 2) IQR outlier capping (optional)
    if do_iqr_outlier_capping:
        if iqr_columns is None:
            iqr_columns = ["absences", "G1", "G2", "G3"]
        out, diag = cap_numeric_outliers_iqr(out, columns=iqr_columns, k=cap_k)
        diagnostics["iqr_outliers"] = diag

    # 3) Categorical standardization
    if do_categorical_standardization:
        if categorical_replacements is None:
            categorical_replacements = {
                # common normalization examples (add more if you discover variants)
                "Yes": "yes", "NO": "no", "No": "no", "No ": "no", " Yes": "yes"
            }
        out = standardize_categorical_strings(
            out,
            lowercase=categorical_lowercase,
            strip_whitespace=True,
            replacements=categorical_replacements
        )
        diagnostics["categorical_standardization"] = pd.DataFrame(
            [{"status": "completed", "n_rows": len(out), "n_cols": out.shape[1]}]
        )

    # 4) Hidden missing token check
    if do_hidden_missing_token_check:
        out, diag = detect_hidden_missing_tokens_in_objects(
            out,
            missing_tokens=hidden_missing_tokens
        )
        diagnostics["hidden_missing_tokens"] = diag

    # 5) Redundancy report among grades
    if do_redundancy_correlation_report:
        if redundant_grade_cols is None:
            redundant_grade_cols = ["G1", "G2", "G3"]
        out, diag = report_redundant_correlated_features(
            out,
            cols=redundant_grade_cols,
            threshold=corr_threshold
        )
        diagnostics["redundant_correlation_pairs"] = diag

    return out, diagnostics
```

---

## E. Example Usage (single line)

```python
clean_df, diag = clean_prepare_dataset(df, set_invalid_to_na=True, cap_k=1.5)
```

Context + Instruction + payload + Response

# **To use in Practical test**:The dataset profile was sent to the OpenAI API together with context and instructions requesting data quality assessment and preprocessing recommendations.

A text-based dataset payload was created using the dataset structure, column information, data types, missing values, duplicate counts and sample records. The payload was combined with task context and instructions before being sent to the OpenAI API for data quality and preprocessing recommendations.

# **Step 9: Review OpenAI Recommendations**

If have practical test question. Otherwise, can skip

In [14]:
# Prompt 1: Review Open AI Recommendations
review_prompt = f"""
The following recommendations were generated from a dataset review:

{response.output_text}

Review each recommendation.

For each recommendation:

1. State:
   - Accept
   - Modify
   - Reject

2. Give a concise reason (1-2 sentences).

3. Focus on:
   - Data quality
   - Missing values
   - Duplicates
   - Outliers
   - Target leakage
   - Feature engineering
   - Machine learning best practices

Return the answer in this format:

Recommendation:
Decision:
Reason:

Keep the answer concise and practical.
"""

review_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="You are a senior data scientist.",
    input=review_prompt
)

print(review_response.output_text)

Recommendation: Normalize categorical string columns (strip whitespace, unify case).
Decision: **Accept**
Reason: Reduces category fragmentation from casing/spacing differences, which directly improves generalization and prevents unseen-category issues at inference.

Recommendation: Validate and optionally cap extreme outliers in `absences` using robust quantiles/IQR.
Decision: **Accept**
Reason: A heavy-tailed `absences` distribution (max far above typical values) can dominate tree splits and increase variance; robust capping improves stability without distorting central tendency.

Recommendation: Target-leakage prevention by dropping grade columns based on the chosen target.
Decision: **Accept**
Reason: If the target is a later grade (commonly `G3`), including earlier grades (`G1`, `G2`) leaks future information and can inflate offline metrics.

Recommendation: Run missing-value sentinel cleanup (empty strings / literal tokens).
Decision: **Modify**
Reason: While `null_count=0` suggests no true missingness, sentinel/empty-string “missing-like” values are common in string fields; the cleanup should be applied only to categorical/object columns (your helper already mostly does this).

Recommendation: Duplicate check (exact duplicates) and drop if found.
Decision: **Accept**
Reason: Even though exact duplicates are reported as 0, an idempotent deduplication guard is low risk and prevents rare downstream bias from accidental repeats.

In [15]:
# Prompt 2: Review Open AI Recommendations

review_prompt = f"""
Below are recommendations generated from a dataset review.

{response.output_text}

For each recommendation:

1. State whether it should be Accepted, Modified, or Rejected.
2. Explain why.
3. Identify any risks or limitations.
"""

review_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="You are a senior data scientist.",
    input=review_prompt
)

print(review_response.output_text)

Below is a recommendation-by-recommendation decision: **Accepted / Modified / Rejected**, with rationale, and risks/limitations.

---

## A. Data Quality Review

### 1) Missing value concerns (Priority: Low)
**Decision: Accepted (as-is)**
1. **Why:** If the profile shows `null_count=0` across all columns, imputation is not necessary. Your only caution is about *non-null sentinels* (e.g., `"NA"`, `""`, `"null"`)—that’s a real-world issue that this recommendation correctly addresses.
2. **Risks / limitations:**
   - If the dataset truly uses only real nulls (and no sentinels), the added runtime checks are redundant.
   - If you only clean empty-string/type issues on `object` columns, you might miss numeric sentinels (e.g., `-1`) unless you also validate numeric domains.

---

### 2) Duplicate record concerns (Priority: Low)
**Decision: Accepted (as-is)**
1. **Why:** “0 exact duplicates” suggests low risk, and keeping a lightweight duplicate drop is safe. It won’t hurt model performance unless there are genuine repeated observations you intend to keep (rare for tabular ML datasets).
2. **Risks / limitations:**
   - If duplicates are semantically meaningful (e.g., repeated measurements that reflect frequency/weights), dropping them changes the effective sample distribution.
   - The recommendation says standard duplicates only—good, since “near-duplicates” can be expensive and subjective.

---

### 3) Potential outlier concerns (notably `absences`, and grade-related fields) (Priority: Medium)
**Decision: Accepted (with a minor modification)**
1. **Why:** Heavy-tailed `absences` (max 75, large std) can destabilize splits and increase variance, especially on small/moderate datasets. Capping/winsorizing via robust statistics is a reasonable *cleaning* step.
2. **Modification:** Specify the cap strategy more carefully (e.g., winsorize at 99th percentile or using IQR with verification plots). For `absences`, I’d generally prefer **quantile-based** capping (e.g., 99th) *or* IQR but validated against domain expectations.
3. **Risks / limitations:**
   - Capping can remove signal if extreme values are genuine and predictive.
   - If `absences` is already bounded by a known encoding rule, it may not be “outliers” in the semantic sense—so clipping too aggressively could degrade accuracy.

---

### 4) Columns redundant / highly correlated (risk of multicollinearity) (Priority: Low)
**Decision: Rejected (as a “data cleaning” action), Accepted as a “modeling note”**
1. **Why:** Multicollinearity is primarily a concern for linear models; tree-based models are much more tolerant. Also, dropping correlated features **requires knowing the modeling approach and target**—which your review explicitly lacks.
2. **Risks / limitations:**
   - Dropping one of `G1/G2/G3` or `Dalc/Walc` without a target-aware rule could inadvertently create leakage or remove important non-redundant information (correlation ≠ redundancy).
   - Keeping everything is safer at the cleaning stage.

---

### 5) Potential target leakage (grades) (Priority: High)
**Decision: Accepted (as-is, but require target-specific confirmation)**
1. **Why:** If the target is final performance (commonly `G3`), then including earlier grades (`G1`, `G2`) is classic leakage. This can inflate offline metrics and fail in production.
2. **Risks / limitations:**
   - The risk depends on **what the prediction goal actually is** and what features will be available at inference time.
   - If the real task is “predict grade using all past exam results including earlier grades,” then dropping might be wrong.
   - Therefore, it must be tied to *your* target definition and data availability.

---

### 6) Inconsistent or non-standard categorical representations (hidden data quality issue) (Priority: High)
**Decision: Accepted (as-is)**
1. **Why:** String categoricals often contain leading/trailing spaces, inconsistent casing, and literal “nan/None” strings. This causes category fragmentation and can create unseen categories at inference.
2. **Risks / limitations:**
   - Lowercasing indiscriminately can be problematic for categoricals where case is meaningful (uncommon, but possible for codes like `"GP"` vs `"gp"`).
   - Casting to `str` can convert real NaNs into `"nan"`—your code handles this by mapping `"nan"/"None"` back to `np.nan`, which mitigates the issue.

---

### 7) Numeric validity checks for score-coded features (Priority: Medium)
**Decision: Modified**
1. **Why:** Validating numeric domain constraints is important, but the “appropriate action” in your review is a bit underspecified: it suggests inferring plausible ranges. That’s doable but must be grounded in dataset documentation or observed coding rules.
2. **Modification:**
   - First run **schema/domain validation**: check min/max, integer-ness for discrete encodings, and detect negative or impossible code values.
   - Only then decide whether clipping is appropriate (and to what bounds).
3. **Risks / limitations:**
   - Without domain knowledge, clipping based only on observed quantiles can mask encoding problems rather than fix them.
   - Some “outliers” in coded features might be legitimate categories (e.g., a special code for missing/unknown) that should become NaN instead of being clipped.

---

## B. Recommended Actions (prioritized list)

### 1) Normalize categorical string columns (strip whitespace, unify case) — Priority High
**Decision: Accepted (as-is)**
- **Why:** Directly addresses fragmentation and unseen-category problems.
- **Risks/limitations:** Lowercasing might not be universally safe for all categorical codes; if you have known case-sensitive IDs, exempt them.

---

### 2) Validate and optionally cap extreme outliers in `absences` — Priority Medium
**Decision: Accepted (with the earlier modification to strategy)**
- **Why:** Stabilizes training and prevents extreme values from dominating.
- **Risks/limitations:** Capping can reduce predictive power if extremes are meaningful; consider winsorization with conservative bounds and evaluate.

---

### 3) Target leakage prevention by dropping grade columns based on chosen target — Priority High
**Decision: Accepted (as-is)**
- **Why:** Correctly prevents leakage when target is one of the grades.
- **Risks/limitations:** Must reflect *true inference-time availability*. If earlier grades are known at prediction time, you should keep them.

---

### 4) Run missing-value sentinel cleanup — Priority Low
**Decision: Accepted (as-is)**
- **Why:** Guards against “null_count=0” blind spots due to sentinel tokens and empty strings.
- **Risks/limitations:** If some legitimate category value is exactly `"na"` or `""`, replacing it would be wrong. Consider using a whitelist/targeted approach if categories include those tokens meaningfully.

---

### 5) Duplicate check (exact duplicates) and drop if found — Priority Low
**Decision: Accepted (as-is)**
- **Why:** Safe and low cost given the profile indicates no duplicates.
- **Risks/limitations:** Same as earlier: if duplicates represent frequency/weights you intended to keep, dropping changes the effective sample distribution.

---

## Note on the provided Python functions
- Overall they align with the recommendations.
- One **limitation**: the categorical cleaner lowercases every `object` categorical. If there are categorical codes where case matters, you’d want a small exception list or a per-column policy.

---

If you tell me (1) the **exact target column** and (2) which columns are available at inference time, I can confirm whether the grade-dropping logic should be exactly as written or requires adjustment.

In [16]:
# Prompt 3: Review Open AI Recommendations

review_prompt = f"""
The following recommendations were generated from a dataset review:

{response.output_text}

Please review each recommendation.

For each recommendation:

1. State whether it should be:
   - Accept
   - Modify
   - Reject

2. Explain the reason for the decision.

3. Consider:
   - Data quality
   - Target leakage
   - Missing values
   - Outliers
   - Feature engineering
   - Machine learning best practices

Present the answer in the following format:

Recommendation:
Decision:
Reason:
"""

review_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
    You are a senior data scientist reviewing recommendations made by a junior analyst.
    Evaluate each recommendation critically and justify your decisions.
    """,
    input=review_prompt
)

print(review_response.output_text)

Recommendation:
Normalize categorical string columns (strip whitespace, unify case).
Decision: **Accept**
Reason:
- **Data quality:** This directly addresses a common hidden issue in “null_count=0” datasets—different representations of the same category (e.g., `"yes"`, `" yes"`, `"Yes"`), which can fragment categories.
- **Missing values:** Doesn’t impute; it reduces downstream mismatch risk.
- **ML best practices:** Especially important if you use one-hot encoding or target encoding—category fragmentation increases sparsity/variance and can harm generalization.
- **Leakage:** No leakage introduced.
- **Outliers:** Not relevant.
- **Modification (minor):** In the provided code, converting to `str` before sentinel handling can turn real missing values into the literal strings `"nan"`/`"None"`. You *do* try to clean `"nan"/"None"` later, but I’d still adjust the order (handle NaNs before `astype(str)`) to be safer.

---

Recommendation:
Validate and optionally cap extreme outliers in `absences` using robust quantiles/IQR (winsorize/cap).
Decision: **Modify**
Reason:
- **Data quality:** The `absences` range (max 75 with mean ~5.7 and std ~8) suggests heavy tails, so outlier validation is warranted.
- **ML best practices:** Capping can help **stability** but it can also remove meaningful signal if high absenteeism is truly predictive. Tree-based models are fairly robust, so wholesale capping may be unnecessary.
- **Best practice:** Prefer **flagging** and comparing model performance (with/without capping) via CV.
- **Modification:**
  - Make capping conditional on whether outliers are likely invalid (e.g., outside plausible bounds for the domain) vs merely rare.
  - Use a conservative cap (e.g., 99th percentile) or winsorize upper tail only, rather than symmetric IQR capping, unless you verify lower-bound issues.

---

Recommendation:
Target-leakage prevention by dropping grade columns based on the chosen target (e.g., predicting `G3` ⇒ drop `G1`, `G2`).
Decision: **Accept**
Reason:
- **Target leakage:** This is the highest-risk item. If the goal is to predict later/final achievement, including earlier grades is typically leakage (the features contain information that would not be available at inference time).
- **ML best practices:** Prevents inflated CV metrics and poor real-world validity.
- **Missing values/outliers:** Not directly relevant.
- **Modification (minor but important):** Your current rule for target=`G1` drops `G2` and `G3` as well. That’s plausible, but in many realistic setups you wouldn’t even have `G2/G3` at inference—so consider letting the user define which columns are *available at prediction time* rather than hardcoding “often not available.” Your “user provides target” approach is good; extending to “allowed feature set” would be more robust.

---

Recommendation:
Run missing-value sentinel cleanup (empty strings / literal tokens).
Decision: **Accept**
Reason:
- **Data quality:** Even if `null_count=0`, categorical sentinels like `""`, `"NA"`, `"N/A"`, `"none"` are common and should be standardized.
- **Missing values:** This improves correctness of missingness handling without forcing imputation.
- **ML best practices:** Reduces the chance that “missing-like” tokens become genuine categories, which can distort splits/encoding.
- **Modification (minor):** Don’t apply to **all columns** by default—your code allows focus on categorical columns, which is safer. Also, consider handling pandas-native missing detection first rather than relying entirely on string matching.

---

Recommendation:
Duplicate check (exact duplicates) and drop if found.
Decision: **Accept**
Reason:
- **Data quality:** Removing exact duplicates is standard hygiene.
- **ML best practices:** Prevents certain models/metrics from being biased by repeated identical rows.
- **Missing/outliers/leakage:** Not directly relevant.
- **Modification (optional):** Since you already rely on profile reporting 0 duplicates, keep it as a safeguard (low overhead). If you later see near-duplicates or conflicting values, then “near-duplicate” handling becomes necessary.

---

If you want, I can also review the provided Python functions for edge cases (e.g., the `astype(str)` → `"nan"` conversion ordering, ensuring numeric columns never accidentally get coerced, and making `absences` capping tail-only by default).

In [17]:
# Prompt 4: Review Open AI Recommendations

review_prompt = f"""
The following recommendations were generated from a dataset review:

{response.output_text}

Review each recommendation and determine whether it should be Accepted, Modified, or Rejected.

Consider the following:

- Prevention of target leakage
- Effect of duplicates
- Treatment of missing values
- Whether outliers represent valid observations
- Whether feature engineering is necessary at this stage
- Whether any predictors should be removed before modelling

Provide clear reasoning for every decision.

Format:

Recommendation:
Decision:
Reason:
"""

review_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
    You are a senior data scientist reviewing recommendations made by a junior analyst.
    Evaluate each recommendation critically and justify your decisions.
    """,
    input=review_prompt
)

print(review_response.output_text)

### 1) Normalize categorical string columns (strip whitespace, unify case)
**Recommendation:** Accept
**Decision:** **Accepted (with modification)**
**Reason:**
- **Missing values:** Not directly, but it reduces *false categories* and “missing-like” inconsistencies (e.g., `" NA"`, `"na "`).
- **Effect on duplicates:** None; orthogonal.
- **Model impact:** This is a common, high-value data quality fix for string categoricals—prevents category fragmentation and unseen-category issues.
- **Whether feature engineering is necessary:** Not required; this is pure cleaning.
- **Modification needed:** In the provided code, the function coerces `NaN` to the string `"nan"` (`astype(str)`), then tries to fix it with `isin(["nan", "None", ...])`. That’s workable but brittle. Prefer: only strip/lowercase non-null entries, e.g., operate via `.where(notna, ...)` or use `df[col] = df[col].str.strip()` without forcing to string first.
- **Priority fit:** This is truly **high** because it directly affects categorical cardinality and split behavior.

---

### 2) Validate and optionally cap extreme outliers in `absences` (winsorize/cap via robust quantiles/IQR)
**Recommendation:** Modify
**Decision:** **Modified (don’t always cap by default; implement as optional + safer default thresholds)**
**Reason:**
- **Whether outliers represent valid observations:** In absence-count data, extremes (e.g., 75) can be legitimate (students who missed many classes). Capping them can remove signal.
- **Effect on ML performance:** Tree models are relatively robust, but heavy tails can still increase variance, especially with small datasets or when using linear models.
- **How to handle correctly:**
  - Do **not** hard-code capping as a “must” operation. Make it **conditional** (e.g., only cap if values exceed plausible domain constraints or if model diagnostics show instability).
  - If you do cap, consider:
    - using a **high quantile** (e.g., 99th) instead of IQR-only when distributions are discrete/heavy-tailed, or
    - first run a **plausibility check**: absences should not exceed known maximum (if known), otherwise treat as valid.
- **Feature engineering necessity:** No; this is still cleaning, but it’s riskier than categorical normalization.
- **So:** Keep the function but change the default application policy (optional, or gated by domain plausibility / validation results).

---

### 3) Target leakage prevention by dropping grade columns based on chosen target (`G1`, `G2`, `G3`)
**Recommendation:** Accept
**Decision:** **Accepted (with modification)**
**Reason:**
- **Prevention of target leakage:** This is the most critical item. If predicting `G3`, using `G1`/`G2` is almost certainly leakage because they are earlier assessments that the final score summarizes or strongly predicts.
- **Effect of duplicates:** None.
- **Missing values:** None.
- **Whether predictors should be removed before modelling:** Yes—**remove** grade features that would not be available at inference. This is explicitly aligned to your “prediction horizon” concept.
- **Modification needed:** The current rule for `target_col="G1"` drops `G2` and `G3`. In many real setups, predicting `G1` from future grades might still be leakage; but whether `G3` is “future” depends on the timestamping available. So:
  - Keep the function, but document that it assumes **chronological leakage** and the user must ensure the horizon makes sense.
  - Also ensure you never drop the actual `target_col` (you aren’t, good).
- **Priority fit:** **High** and should remain default when target is set.

---

### 4) Run missing-value sentinel cleanup (empty strings / literal tokens like `""`, `"NA"`, `"N/A"`, etc.)
**Recommendation:** Accept
**Decision:** **Accepted (with modification)**
**Reason:**
- **Missing values:** Even though `null_count=0`, sentinel tokens are a very common “hidden missing” pattern in object columns. This recommendation is still valid.
- **Effect on duplicates:** None.
- **Effect on ML performance:** Reduces spurious categories (“na” as a category).
- **Modification needed (important):** The current `replace_missing_sentinels()` replaces sentinels across the columns passed. It defaults to operating on **all columns** if `categorical_cols` isn’t provided (you set `cols = df.columns`). However, the code checks `dtype == "object"` before replacing, so it will not touch numeric columns directly—still OK.
  - More importantly, `clean_dataset()` currently **does** both `replace_missing_sentinels` and `clean_categorical_whitespace_case`. Because the latter does `astype(str)`, the string `"nan"` problem can interfere unless you apply sentinel replacement carefully first and in the right order.
  - You should enforce a safe order: **(1) replace sentinels (including empty string) while preserving real NaNs**, then **(2) normalize strings** on non-null only.
- **So:** Keep as accepted, but adjust ordering/implementation robustness.

---

### 5) Duplicate check (exact duplicates) and drop if found
**Recommendation:** Modify
**Decision:** **Modified (keep as guard, but don’t rely on it; avoid blanket drops if you have legitimate repeated rows)**
**Reason:**
- **Effect of duplicates:** If the dataset truly has no duplicates (profile says 0), dropping exact duplicates won’t change anything.
- **Whether to accept removal:** Generally safe **if** duplicates are truly redundant.
- **Potential risk:** In some datasets, identical rows can represent legitimate multiple events (e.g., repeated observations). Dropping could remove true sample multiplicity.
- **Modification needed:**
  - Keep the check, but default behavior could be “detect and log” rather than always “drop,” unless you’re confident each row is a unique entity.
  - If rows represent students, exact duplicates likely indicate ingestion issues—but this should be confirmed.
- **Given the profile reports 0 duplicates**, this is low priority.

---

## Review of the provided Python cleaning code (cross-cutting decisions)
**Overall Decision:** **Mostly Accepted, but require modifications to reduce brittleness**
- **Categorical normalization:** Fix `astype(str)` approach to avoid turning missing values into `"nan"` strings (use non-null masking).
- **Ordering between sentinel replacement and normalization:** Ensure sentinel replacement happens before any transformations that coerce NaNs to strings.
- **Outlier capping:** Make it truly optional or gated by plausibility/domain checks or validation diagnostics.

---

## Summary Decisions Table (for quick grading)
**Recommendation:** 1) Normalize categoricals
- **Decision:** **Accepted (with modification)**

**Recommendation:** 2) Cap `absences` outliers
- **Decision:** **Modified (optional / gated; don’t always cap)**

**Recommendation:** 3) Drop grade columns for leakage
- **Decision:** **Accepted (with modification / horizon-awareness)**

**Recommendation:** 4) Sentinel missing cleanup
- **Decision:** **Accepted (with modification / ordering robustness)**

**Recommendation:** 5) Drop exact duplicates
- **Decision:** **Modified (guard/log-first unless entity uniqueness is guaranteed)**

###Mock question (quality of understanding): Review against the need for each recommendation.

**Sample answer**
1. Ok to remove duplicate if any.
2. G1 G2 G3 will be removed later.
3. Combining or reduction of predictors is not needed at this stage, not an issue for XGB.
4. Dropping outlier is premature at this stage, especially when we are interested in more special cases. [For example, age has outliers, but as we can observe later, older students had higher chance to failing subjects. It is a valid signal, not a noise.]

**Check in with your tutor, to see if your understanding is aligned with good practices of data science.**

# **Step 10: Data Cleaning Prompt (Universal template)**
With python code to run later

In [39]:
# =====================================================
# STEP: Generate Data Cleaning Code
# Universal Cleaning Prompt
# =====================================================

cleaning_prompt = f"""
DATASET PROFILE:

{payload_text}

OPENAI RECOMMENDATIONS:

{response.output_text}

TASK:

Generate a practical data cleaning solution based on the dataset profile and recommendations.

First provide:

A. Cleaning Plan

Use a numbered list.

For each item provide:

Issue:
Action:
Reason:
Priority:

Keep explanations concise and practical.

Then provide:

B. Python Code

Requirements:

1. Generate ONE complete Python code block.
2. Assume the dataframe is called df.
3. Store the cleaned dataframe as df_clean.
4. Include comments explaining major cleaning steps.
5. Implement the recommended cleaning actions where appropriate.
6. Perform only data cleaning tasks.
7. Use sensible data science judgement when generating the code.
8. Ensure the code is executable in a single Jupyter/Colab notebook cell.
9. The final line should display df_clean.

Do NOT perform:

- Encoding
- Scaling
- Train/Test Split
- Feature Selection
- Modelling

Focus only on preparing a cleaned dataset ready for the next machine learning step.

Output format:

A. Cleaning Plan

B. Python Code
"""

cleaning_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
You are a senior data scientist.

Generate practical and accurate data-cleaning code.

Use the dataset profile and recommendations to decide what cleaning steps should actually be implemented.

Avoid unnecessary cleaning actions.

The cleaning plan should be easy for a student to read during a practical test.

The Python solution should be a single executable code block that can be copied into one notebook cell and run immediately.
""",
    input=cleaning_prompt
)

print(cleaning_response.output_text)

## A. Cleaning Plan

1) **Issue:** No missing values reported, but hidden “missing-like” categorical values (empty/whitespace) can exist.
   **Action:** Trim whitespace for all categorical columns; convert empty/whitespace-only strings to real `NaN`; normalize casing to lower-case.
   **Reason:** Prevents subtle category fragmentation (e.g., `"yes "` vs `"yes"`).
   **Priority:** Medium

2) **Issue:** Numeric sanity/outliers risk: `absences` has a wide range (max 75) and grades may have inconsistent bounds (e.g., `G1` min 3 while `G2/G3` min 0).
   **Action:**
   - Coerce numeric columns to numeric (errors -> `NaN` only if something is truly malformed).
   - For `absences`, set negative values to `NaN` and cap extreme high values using a high quantile (winsorize).
   - Clip grade columns `G1/G2/G3` to `[0, 20]`.
   **Reason:** Removes clearly invalid values and reduces leverage of extreme outliers while keeping most data intact.
   **Priority:** Medium

3) **Issue:** Potential label leakage if the target is a grade column (`G1`, `G2`, or `G3`) and other grade columns are used. Target is unknown.
   **Action:** Provide a safe, conditional scaffold: if you set `target_col` in code, drop the *other* grade columns when the target is one of the grades.
   **Reason:** Prevents leakage once the target is specified; does nothing otherwise.
   **Priority:** High (conditional)

4) **Issue:** Duplicates are reported as 0.
   **Action:** No duplicate removal performed.
   **Reason:** Avoid unnecessary changes.
   **Priority:** Low


## B. Python Code
```python
import numpy as np
import pandas as pd

# -----------------------------
# Cleaning steps based on dataset profile + recommendations
# -----------------------------

# If you know the target column, set it here (e.g., "G3"). Otherwise leave as None.
target_col = None  # <-- change if needed (conditional leakage prevention)

df_clean = df.copy()

# 1) String hygiene for categorical columns
cat_cols = df_clean.select_dtypes(include=["object"]).columns.tolist()
for c in cat_cols:
    # Convert to string-like safely, then trim whitespace
    df_clean[c] = df_clean[c].astype("object")
    # Replace empty/whitespace-only with NaN
    df_clean[c] = df_clean[c].replace(r'^\s*$', np.nan, regex=True)
    # Normalize whitespace and casing
    df_clean[c] = df_clean[c].astype(str).str.strip().str.lower()
    df_clean[c] = df_clean[c].replace("nan", np.nan)

# 2) Numeric sanity checks & outlier handling
num_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()

# Coerce numeric columns (keeps valid numerics; converts truly malformed entries to NaN)
for c in num_cols:
    df_clean[c] = pd.to_numeric(df_clean[c], errors="coerce")

# absences: no negatives; cap extreme upper tail (robust winsorization)
if "absences" in df_clean.columns:
    neg_mask = df_clean["absences"] < 0
    if neg_mask.any():
        df_clean.loc[neg_mask, "absences"] = np.nan

    # Cap high tail to reduce extreme leverage while retaining most values
    q = df_clean["absences"].quantile(0.995)
    if pd.notna(q):
        df_clean["absences"] = np.where(df_clean["absences"] > q, q, df_clean["absences"])

# Grades: clip to plausible [0, 20] range (conservative given profile max around 19-20)
for g in ["G1", "G2", "G3"]:
    if g in df_clean.columns:
        df_clean[g] = df_clean[g].clip(lower=0, upper=20)

# 3) Conditional leakage prevention if target is one of the grade columns
if target_col is not None and target_col in ["G1", "G2", "G3"]:
    other_grades = [g for g in ["G1", "G2", "G3"] if g != target_col and g in df_clean.columns]
    df_clean = df_clean.drop(columns=other_grades, errors="ignore")

# Final check: keep shape changes only from cleaning actions above
df_clean

# Display cleaned dataframe
df_clean
```

# **Step 10-1 : Copy the python code output from the prompt to do the cleaning.**

In [40]:
import numpy as np
import pandas as pd

# -----------------------------
# Cleaning steps based on dataset profile + recommendations
# -----------------------------

# If you know the target column, set it here (e.g., "G3"). Otherwise leave as None.
target_col = None  # <-- change if needed (conditional leakage prevention)

df_clean = df.copy()

# 1) String hygiene for categorical columns
cat_cols = df_clean.select_dtypes(include=["object"]).columns.tolist()
for c in cat_cols:
    # Convert to string-like safely, then trim whitespace
    df_clean[c] = df_clean[c].astype("object")
    # Replace empty/whitespace-only with NaN
    df_clean[c] = df_clean[c].replace(r'^\s*$', np.nan, regex=True)
    # Normalize whitespace and casing
    df_clean[c] = df_clean[c].astype(str).str.strip().str.lower()
    df_clean[c] = df_clean[c].replace("nan", np.nan)

# 2) Numeric sanity checks & outlier handling
num_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()

# Coerce numeric columns (keeps valid numerics; converts truly malformed entries to NaN)
for c in num_cols:
    df_clean[c] = pd.to_numeric(df_clean[c], errors="coerce")

# absences: no negatives; cap extreme upper tail (robust winsorization)
if "absences" in df_clean.columns:
    neg_mask = df_clean["absences"] < 0
    if neg_mask.any():
        df_clean.loc[neg_mask, "absences"] = np.nan

    # Cap high tail to reduce extreme leverage while retaining most values
    q = df_clean["absences"].quantile(0.995)
    if pd.notna(q):
        df_clean["absences"] = np.where(df_clean["absences"] > q, q, df_clean["absences"])

# Grades: clip to plausible [0, 20] range (conservative given profile max around 19-20)
for g in ["G1", "G2", "G3"]:
    if g in df_clean.columns:
        df_clean[g] = df_clean[g].clip(lower=0, upper=20)

# 3) Conditional leakage prevention if target is one of the grade columns
if target_col is not None and target_col in ["G1", "G2", "G3"]:
    other_grades = [g for g in ["G1", "G2", "G3"] if g != target_col and g in df_clean.columns]
    df_clean = df_clean.drop(columns=other_grades, errors="ignore")

# Final check: keep shape changes only from cleaning actions above
df_clean

# Display cleaned dataframe
df_clean

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,gp,f,18,u,gt3,a,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6.0,5,6,6
1,gp,f,17,u,gt3,t,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4.0,5,5,6
2,gp,f,15,u,le3,t,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10.0,7,8,10
3,gp,f,15,u,gt3,t,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2.0,15,14,15
4,gp,f,16,u,gt3,t,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4.0,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,ms,m,20,u,le3,a,2,2,services,services,course,other,1,2,2,no,yes,yes,no,yes,yes,no,no,5,5,4,4,5,4,11.0,9,9,9
391,ms,m,17,u,le3,t,3,1,services,services,course,mother,2,1,0,no,no,no,no,no,yes,yes,no,2,4,5,3,4,2,3.0,14,16,16
392,ms,m,21,r,gt3,t,1,1,other,other,course,other,1,1,3,no,no,no,no,no,yes,no,no,5,5,3,3,3,3,3.0,10,8,7
393,ms,m,18,r,le3,t,3,2,services,other,course,mother,3,1,0,no,no,no,no,no,yes,yes,no,4,4,1,3,4,5,0.0,11,12,10
394,ms,m,19,u,le3,t,1,1,other,at_home,course,father,1,1,0,no,no,no,no,yes,yes,yes,no,3,2,3,3,3,5,5.0,8,9,9

# **Step 10-2: To check data after cleaning**

In [43]:
# What to check after cleaning:
# 1. Did the number of rows stay the same?
# 2. Did the discount columns disappear?
# 3. Are there missing values that still need attention?
# 4. Does Price_SGD still exist as the target column?

print('Original rows:', df.shape[0])
print('Cleaned rows:', df_clean.shape[0])

print('\nMissing values after cleaning:')
missing_after_cleaning = df_clean.isna().sum()
display(missing_after_cleaning.sort_values(ascending=False).head(10))

print('\nColumns after cleaning:')
print(df_clean.columns.tolist())

Original rows: 395
Cleaned rows: 395

Missing values after cleaning:

school     0
sex        0
age        0
address    0
famsize    0
Pstatus    0
Medu       0
Fedu       0
Mjob       0
Fjob       0
dtype: int64

Columns after cleaning:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences', 'G1', 'G2', 'G3']

# **Save clean dataset as .csv file for next session**

In [46]:
df_clean.to_csv('cleaned_Predicting Number of Failed Subjects.csv', index=False)

print('Saved cleaned dataset as cleaned_Predicting Number of Failed Subjects.csv')
print('You can use this file in Session 2.')

#Task: Do you know where the csv file is?

Saved cleaned dataset as cleaned_Predicting Number of Failed Subjects.csv
You can use this file in Session 2.

# **Step 11: Create Target (Special Target Engineering)**

# **Check points:**

print(df.columns.tolist())

1. Is there a target column already?
2. Does the question specify a target?
3. Do I need to engineer a new target?
4. Could any columns cause target leakage?

**Open AI to help which target to used (With prompt)**


Scenario 1: Target Already exists
| Dataset | Target |
|----------|----------|
| House Prices | price |
| Customer Churn | churn |
| Employee Attrition | attrition |
| Insurance | charges |

Scenario 2: Instructor Tells you how to create target

Create a target indicating whether a customer is high risk.

# **Another Prompt for target recommendation**

In [44]:
# Open AI prompt for target recommendation

target_prompt = f"""
Review the dataset profile below.

DATASET PROFILE:

{payload_text}

Recommend a suitable target variable for machine learning.

Explain:

1. Which column(s) should be used.
2. Whether the problem is:
   - Regression
   - Classification
3. Whether target engineering is needed.
4. Any target leakage risks.
5. Provide Python code to create the target.

Keep the explanation concise.
"""

target_response = client.responses.create(
    model="gpt-5.4-nano",
    instructions="""
    You are a senior data scientist.
    """,
    input=target_prompt
)

print(target_response.output_text)

### Recommended target
Use **`G3`** as the target (final grade in Math, typically 0–20).

This keeps the task aligned with the dataset’s semantics: `G1` and `G2` are earlier grades, while `G3` is the outcome you ultimately care about.

---

## 1) Which column(s) should be used
- **Primary target:** `G3` (recommended)
- Optional (but avoid leakage for most models): `G1`, `G2`
  - If you want to *predict G3*, you generally keep **only `G3`** as target.
  - You can still use `G1`/`G2` as **features** if your real-world scenario “knows current/previous grades”. If not, exclude them.

**Suggested feature set for a leakage-minimized “student-time” setting:** all columns **except** `G3` (and consider also excluding `G1`, `G2` unless they are known at prediction time).

---

## 2) Whether the problem is regression or classification
- **Regression:** `G3` as a continuous numeric grade (most direct)
- **Classification (optional):** binarize or categorize `G3` (e.g., pass/fail), but only if you have a business threshold.

Given the profile shows numeric `G3`, **regression is the best default**.

---

## 3) Whether target engineering is needed
- **No**, if you use `G3` directly for regression.
- **Optional** only for classification/bucketing (not required for regression).

---

## 4) Target leakage risks
Main risk: **using later outcome information to predict the outcome**.
- `G3` is the target; obviously exclude it from features.
- **`G1` and `G2`** are *earlier exams*, so they are **not “future leakage”**—but they can be considered **proxy information**.
  - If your prediction is intended *before* those grades are available, exclude `G1`/`G2`.
  - If they are available at prediction time, including them is acceptable (but may inflate performance).

---

## 5) Python code to create the target

### Regression target (recommended)
```python
import pandas as pd

# df = your dataframe
y = df['G3'].astype(float)          # target for regression
```

### (Optional) Classification target: pass/fail by threshold
Example: pass if `G3 >= 10` (adjust threshold as needed):
```python
y_cls = (df['G3'] >= 10).astype(int)  # 1=pass, 0=fail
```

If you tell me whether the real-world prediction happens **before or after** `G1/G2` are known, I can recommend the safest feature inclusion/exclusion.

In [ ]:
# Does the dataset already contain a target column?
# Scenario 1 Target already exists. This case Target column = price
# ============================================================
# SCenario 1: CREATE TARGET
# ============================================================

target_col = "price"

y = df[target_col]

X = df.drop(columns=[target_col])

In [ ]:
# Need to create a new target as dataset doesn't contain target column.
# Scenario 2 Instructor tell you how to create the target eg. "num_failed_subjects"
# ============================================================
# SCenario 2: CREATE TARGET
# ============================================================

# Create target
df["num_failed_subjects"] = (
    (df[["G1", "G2", "G3"]] < 10)
    .sum(axis=1)
)

# Define target and predictors
y = df["num_failed_subjects"]

X = df.drop(columns=["num_failed_subjects"])

# Quick checks
print("Target shape:", y.shape)
print("Predictor shape:", X.shape)
print(y.value_counts().sort_index())

display(
    df[["G1", "G2", "G3", "num_failed_subjects"]].head()
)

# Or another example
#df["high_risk"] = (
#    (df["late_payments"] > 3)
#).astype(int)
#``

Target shape: (395,)
Predictor shape: (395, 33)
num_failed_subjects
0    221
1     30
2     44
3    100
Name: count, dtype: int64

   G1  G2  G3  num_failed_subjects
0   5   6   6                    3
1   5   5   6                    3
2   7   8  10                    2
3  15  14  15                    0
4   6  10  10                    1

Target shape: (395,) => 395 rows & 1 targte variable (y)

Predictor shape: (395,33) => 395 students and 33 predictor columns (X)

0    221   => 220 students failed 0 subjects. Value_counts () help to answer whether target balance or imbalanced?

The target variable ranges from 0 to 3 failed subjects.

Most students have 0 failed subjects, while relatively fewer students have 2 or 3 failed subjects. This suggests some imbalance in the target distribution, which should be considered when evaluating model performance.


##Step 3) Create the target: number of failed subjects (special target)

Here you convert **three subject grades** into **one target**:

- A subject is considered **failed** when grade `< 10`.
- You count how many of the three subjects are failed.

### Common mistakes to avoid
- Using `<= 10` by accident (that changes the definition).
- Counting missing values as fails (check for missing grades first).
- Forgetting to confirm the **range** of the new target (it should usually be 0–3).


##Step 4) Visual check of subject grades (G1, G2, G3)

**Purpose:** quickly see the grade distribution (0–20) for each subject.

What you should notice:
- Are grades skewed towards high or low?
- Are there many values below 10 (fails)?
- Are there weird values outside 0–20 (data quality issue)?

If there are values outside the expected range, you should investigate before modelling.

In [ ]:
# ------------------------------------------------------------
# TARGET ENGINEERING (special case)
# Code for Step 3 and 4
# Target = count of failed subjects based on G1/G2/G3 < 10
# This is still REGRESSION (numeric target), but values are discrete.
# ------------------------------------------------------------

# --------------------------------------------
# Count number of subjects with score < 10
# from G1, G2, G3 (0 to 3)
# --------------------------------------------
grade_cols = ["G1", "G2", "G3"]

# True/False per subject, then sum across subjects (row-wise)
df["num_failed_subjects"] = (df[grade_cols] < 10).sum(axis=1)

# quick check
df[grade_cols + ["num_failed_subjects"]].head()
# --------------------------------------------
# Hist plots (3 by 1) for G1, G2, G3
# Use matplotlib only (no seaborn)
# --------------------------------------------
import matplotlib.pyplot as plt

fig, axs = plt.subplots(3, 1, figsize=(10, 10), sharex=True)

axs[0].hist(df["G1"].dropna(), bins=range(0, 22), edgecolor="black")
axs[0].set_title("G1")

axs[1].hist(df["G2"].dropna(), bins=range(0, 22), edgecolor="black")
axs[1].set_title("G2")

axs[2].hist(df["G3"].dropna(), bins=range(0, 22), edgecolor="black")
axs[2].set_title("G3")

for ax in axs:
    ax.set_xlim(-0.5, 20.5)

plt.tight_layout()
plt.show()

# Quick sanity check you should do (in your own notes/report):
# - What are the unique values of the target?
# - What is the proportion of 0, 1, 2, 3?
# This helps you understand if the dataset is imbalanced by count.


##Step 5) Create the target: number of failed subjects (special target)

Here you convert **three subject grades** into **one target**:

- A subject is considered **failed** when grade `< 10`.
- You count how many of the three subjects are failed.

### Common mistakes to avoid
- Using `<= 10` by accident (that changes the definition).
- Counting missing values as fails (check for missing grades first).
- Forgetting to confirm the **range** of the new target (it should usually be 0–3).

In [ ]:
# ------------------------------------------------------------
# TARGET ENGINEERING (special case)
# Target = count of failed subjects based on G1/G2/G3 < 10
# This is still REGRESSION (numeric target), but values are discrete.
# ------------------------------------------------------------
# Optional: also plot the target distribution (0–3)
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 4))
plt.hist(df["num_failed_subjects"].dropna(), bins=[-0.5, 0.5, 1.5, 2.5, 3.5], edgecolor="black")
plt.xticks([0, 1, 2, 3])
plt.title("Number of failed subjects (score < 10) across G1, G2, G3")
plt.xlabel("num_failed_subjects")
plt.ylabel("count")
plt.show()

# Quick sanity check you should do (in your own notes/report):
# - What are the unique values of the target?
# - What is the proportion of 0, 1, 2, 3?
# This helps you understand if the dataset is imbalanced by count.

###Useful code, for plotting predictors against categorical-type (including our count of subjects) prediction, to spot meaningful correlations and outliers.

In [ ]:
# ============================================================
# Jitter plot: NUMERIC features vs DISCRETE target (fast)
# x = target classes, y = numeric values (one row facet per feature)
# ============================================================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def jitter_numeric_fast(
    df: pd.DataFrame,
    target_col: str,
    num_cols: list[str] | None = None,
    order: list | None = None,
    max_features: int = 12,
    sample: int | None = 8000,
    max_classes: int = 12,
    class_order: str = "auto",  # "auto" | "sorted" | "freq"
    dropna_target: bool = True,
    dropna_feature: bool = True
):
    """
    Fast jitter plot for numeric features vs a discrete target.

    x = target classes
    y = numeric feature values (one facet per feature)

    Works for:
    - integer-coded targets (e.g. 0,1,2,3 or 1..5)
    - categorical/string targets (e.g. 'Low','Med','High')
    """

    if target_col not in df.columns:
        raise KeyError(f"target_col='{target_col}' not found in df")

    d = df.copy()

    # Drop missing target (usually safest)
    if dropna_target:
        d = d.dropna(subset=[target_col])

    # Auto-detect numeric columns (exclude target)
    if num_cols is None:
        num_cols = d.select_dtypes(include=[np.number]).columns.tolist()
        num_cols = [c for c in num_cols if c != target_col]

    # Keep only existing numeric columns
    num_cols = [c for c in num_cols if c in d.columns and c != target_col]
    if len(num_cols) == 0:
        raise ValueError("No numeric columns found to plot (after excluding target_col).")

    num_cols = num_cols[:max_features]

    # Decide x-axis order for target classes
    if order is None:
        y = d[target_col]

        # Ordered categorical: respect its category order (cap to max_classes)
        if isinstance(y.dtype, pd.CategoricalDtype) and y.dtype.ordered:
            order = list(y.cat.categories)
            if len(order) > max_classes:
                order = y.value_counts().head(max_classes).index.tolist()

        # Numeric target: prefer sorted unique (cap to max_classes)
        elif pd.api.types.is_numeric_dtype(y):
            uniq = pd.unique(y.dropna())
            order = sorted(uniq.tolist())
            if len(order) > max_classes:
                order = sorted(y.value_counts().head(max_classes).index.tolist())

        # String / object target: most frequent classes
        else:
            vc = y.astype("object").value_counts(dropna=False)
            order = vc.head(max_classes).index.tolist()
            if class_order == "sorted":
                order = sorted(order)
            elif class_order == "freq":
                order = order
            else:
                # auto: keep freq order
                order = order

    # Filter to chosen classes
    d = d[d[target_col].isin(order)].copy()

    # Sample once for speed
    if sample is not None and len(d) > sample:
        d = d.sample(sample, random_state=42)

    # Long form
    frames = []
    for c in num_cols:
        tmp = d[[target_col, c]].copy()
        if dropna_feature:
            tmp = tmp.dropna(subset=[c])
        tmp = tmp.rename(columns={c: "value"})
        tmp["feature"] = c
        frames.append(tmp[[target_col, "feature", "value"]])

    long_df = pd.concat(frames, ignore_index=True)

    # Force target order in seaborn
    long_df[target_col] = pd.Categorical(long_df[target_col], categories=order, ordered=True)

    g = sns.catplot(
        data=long_df,
        x=target_col,
        y="value",
        row="feature",
        kind="strip",
        order=order,
        jitter=True,
        height=2.2,
        aspect=3.2,
        sharey=False
    )

    g.set_axis_labels(f"{target_col} (classes: {order})", "Numeric value")
    g.set_titles("{row_name}")
    plt.tight_layout()
    plt.show()

    return order, num_cols


# Example:
order_used, num_cols_used = jitter_numeric_fast(df, target_col="num_failed_subjects", sample=15000)
print(order_used, num_cols_used)

In [ ]:
# ============================================================
# Jitter plot: CATEGORICAL features vs DISCRETE target (fast)
# x = target classes, y = category levels (one row facet per feature)
# ============================================================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def jitter_categorical_fast(
    df: pd.DataFrame,
    target_col: str,
    cat_cols: list[str] | None = None,
    order: list | None = None,
    max_features: int = 12,
    sample: int | None = 8000,
    max_classes: int = 12,
    class_order: str = "auto",      # "auto" | "sorted" | "freq"
    dropna_target: bool = True,
    top_k: int = 15,                # keep top categories per feature, rest -> "Other"
    dropna_feature: bool = False,   # if False, show missing as "(Missing)"
    missing_label: str = "(Missing)",
    show_other: bool = True
):
    """
    Fast jitter plot for categorical features vs a discrete target.

    x = target classes
    y = categorical feature levels (one facet per feature)

    Notes:
    - For each categorical feature, rare categories are collapsed into "Other" (top_k kept).
    - Missing can be shown explicitly as missing_label.
    """

    if target_col not in df.columns:
        raise KeyError(f"target_col='{target_col}' not found in df")

    d = df.copy()

    # Drop missing target (usually safest)
    if dropna_target:
        d = d.dropna(subset=[target_col])

    # Decide x-axis order for target classes
    if order is None:
        y = d[target_col]

        if isinstance(y.dtype, pd.CategoricalDtype) and y.dtype.ordered:
            order = list(y.cat.categories)
            if len(order) > max_classes:
                order = y.value_counts().head(max_classes).index.tolist()

        elif pd.api.types.is_numeric_dtype(y):
            uniq = pd.unique(y.dropna())
            order = sorted(uniq.tolist())
            if len(order) > max_classes:
                order = sorted(y.value_counts().head(max_classes).index.tolist())

        else:
            vc = y.astype("object").value_counts(dropna=False)
            order = vc.head(max_classes).index.tolist()
            if class_order == "sorted":
                order = sorted(order)
            elif class_order == "freq":
                order = order
            else:
                order = order

    # Filter to chosen classes
    d = d[d[target_col].isin(order)].copy()

    # Sample once for speed
    if sample is not None and len(d) > sample:
        d = d.sample(sample, random_state=42)

    # Auto-detect categorical columns
    if cat_cols is None:
        cat_cols = d.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
        cat_cols = [c for c in cat_cols if c != target_col]

    cat_cols = [c for c in cat_cols if c in d.columns and c != target_col]
    if len(cat_cols) == 0:
        raise ValueError("No categorical columns found to plot (after excluding target_col).")

    cat_cols = cat_cols[:max_features]

    # Build long form with per-feature top_k collapsing
    frames = []
    for c in cat_cols:
        tmp = d[[target_col, c]].copy()

        if dropna_feature:
            tmp = tmp.dropna(subset=[c])
            tmp[c] = tmp[c].astype("object")
        else:
            tmp[c] = tmp[c].astype("object").fillna(missing_label)

        # Collapse rare categories to Other
        vc = tmp[c].value_counts(dropna=False)
        keep = vc.head(top_k).index.tolist()

        if show_other:
            tmp[c] = tmp[c].where(tmp[c].isin(keep), other="Other")
            # Make a stable y-order: keep list + "Other" (if present)
            y_order = [k for k in keep if k in tmp[c].unique()]
            if "Other" in tmp[c].unique() and "Other" not in y_order:
                y_order.append("Other")
        else:
            tmp = tmp[tmp[c].isin(keep)].copy()
            y_order = [k for k in keep if k in tmp[c].unique()]

        tmp = tmp.rename(columns={c: "value"})
        tmp["feature"] = c
        tmp["_y_order"] = [y_order] * len(tmp)
        frames.append(tmp[[target_col, "feature", "value", "_y_order"]])

    long_df = pd.concat(frames, ignore_index=True)

    # Force target order in seaborn
    long_df[target_col] = pd.Categorical(long_df[target_col], categories=order, ordered=True)

    # Faceted strip plot. We cannot pass a different y-order per facet directly,
    # so we do a small loop to respect each feature's y-order.
    features = long_df["feature"].unique().tolist()
    n = len(features)

    fig, axes = plt.subplots(n, 1, figsize=(12, max(2.2 * n, 2.2)), sharex=True)
    if n == 1:
        axes = [axes]

    for ax, feat in zip(axes, features):
        sub = long_df[long_df["feature"] == feat].copy()
        y_order = sub["_y_order"].iloc[0]

        sns.stripplot(
            data=sub,
            x=target_col,
            y="value",
            order=order,
            jitter=True,
            size=3,
            ax=ax
        )

        ax.set_title(feat)
        ax.set_ylabel("Category")
        ax.set_xlabel("")
        ax.set_yticks(range(len(y_order)))
        ax.set_yticklabels(y_order)

    axes[-1].set_xlabel(f"{target_col} (classes: {order})")
    plt.tight_layout()
    plt.show()

    return order, cat_cols


# Example:
order_used, cat_cols_used = jitter_categorical_fast(df, target_col="num_failed_subjects", sample=15000, top_k=12)
print(order_used, cat_cols_used)

### What to look for in quick checks

Standard checks you should be able to explain:
- `df.shape`: how many rows and columns (scale)
- `df.info()`: data types and missing values (readiness)
- `df.describe(include="all")`: typical values, outliers, rare categories (risk)

Common edge cases:
- `0` might mean a real value, or it might mean *missing coded as 0* (depends on the dataset).
- Some columns look numeric but are actually IDs or codes. Treat those carefully.

In [ ]:
# Class balance (important for evaluation choices)
target_col = "num_failed_subjects"
df[target_col].value_counts(normalize=True)

In [ ]:
X = df.drop(columns=[target_col, "G2", "G3", "G1"])
y = df[target_col]
X.shape, y.shape


##Step 6) Split into train and test sets

**Goal:** ensure you evaluate on unseen data.

Revision reminders:
- Use the same `random_state` for reproducibility.
- For regression, you usually do **not** stratify (unless you bucket the target).
- Keep the test set untouched until final evaluation.

In [ ]:
# ------------------------------------------------------------
# TRAIN / TEST SPLIT
# Keep the test set for final evaluation only.
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.1,
    random_state=42,
    stratify=y  # important for imbalanced
)

In [ ]:
#value count for y_train and y_test
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

### Train/test split: what you are protecting against

**Standard definition:**  
A train/test split separates data you learn from (train) and data you hold back for final checking (test). This helps you estimate how well the model will work on new cases.

**Why `stratify=y` matters:**  
If classes are imbalanced, stratification keeps the class ratios similar in train and test.

**Edge case:**  
If a class is extremely rare, stratified splitting can fail or create tiny class counts. In that case, you may need a different split strategy or simpler target grouping.


##Step 7) Preprocessing (critical for mixed columns)

Most real datasets contain both:
- numeric columns (need scaling sometimes, missing values handling)
- categorical columns (need encoding, missing values handling)

**Tip:** In a practical test, a clean `ColumnTransformer` + `Pipeline` is often the best answer because:
- it reduces leakage,
- it ensures the same steps apply to train and test,
- it makes your workflow reproducible.

In [ ]:
# ------------------------------------------------------------
# PREPROCESSOR
# Make sure preprocessing is inside a Pipeline to avoid leakage.
# ------------------------------------------------------------

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

# Identify columns by dtype
num_features = X_train.select_dtypes(include=[np.number]).columns.tolist()
cat_features = X_train.select_dtypes(exclude=[np.number]).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", num_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_features),
    ],
    remainder="drop"
)

num_features[:10], cat_features[:10]


##Step 8) Build a model pipeline

**Revision goal:** You should be able to explain:
- What the preprocessor does
- What the model does
- Why a pipeline prevents mistakes

### Special note for this target
Even though the true target is a small set of integers, your regression model might output non-integers.
That is normal.

If the task requires integer predictions, you can *post-process* predictions (rounding),
but only do this if instructed, and always state the trade-off (it can change metrics).

### Evaluate using regression metrics

In a practical test, explain metrics in simple terms:

- **MAE**: average absolute error (easy to explain in grade points)
- **RMSE**: penalises large errors more strongly
- **R²**: how much variance is explained (can be misleading if target range is small)

### Edge case reminder
Because your target range is small (often 0–3), R² may look low even if errors are small.
So you should always report MAE or RMSE too.

In [ ]:
# ------------------------------------`
# 0. NOTE: This block takes quite a while to run, do it before moving onto explanation of code
# ------------------------------------

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import ShuffleSplit
cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=42)
# -------------------------------------------
# 1. Create pipelines for both models
# -------------------------------------------

pipe_rf = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(random_state=42))
])

pipe_xgb = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(
        random_state=42))
])

# -------------------------------------------
# 2. Define parameter grids
# Keep them small for speed and simplicity
# -------------------------------------------

param_grid_rf = {
  "regressor__n_estimators": [50, 200],
  'regressor__max_depth':[5,10, None],
  'regressor__criterion':['squared_error', 'absolute_error']
}

param_grid_xgb = {
    "regressor__n_estimators": [50, 200],
  'regressor__max_depth':[2,4,6],
  'regressor__eval_metric':['rmse', 'mae']
}

# -------------------------------------------
# 3. Create GridSearchCV objects
# -------------------------------------------

gs_rf = GridSearchCV(
    estimator=pipe_rf,
    param_grid=param_grid_rf,
    cv=cv,
    scoring="neg_mean_absolute_error",
    n_jobs=-1,
    verbose=1
)

gs_xgb = GridSearchCV(
    estimator=pipe_xgb,
    param_grid=param_grid_xgb,
    cv=cv,
    scoring="neg_mean_absolute_error",
    n_jobs=-1,
    verbose=1
)

# -------------------------------------------
# 4. Fit both models
# (Students can run one at a time if needed)
# -------------------------------------------e

gs_rf.fit(X_train, y_train)
print("Random Forest grid search complete.")

gs_xgb.fit(X_train, y_train)
print("XGBoost grid search complete.")

In [ ]:
#setup a results df to hold training and test scores
#at this point, you should already decide what scoring metric you going to use
#regression: r2, mae, rmse, mape

#setup our 'lab book' to store all scores across various "engineering" or PDCA cycles, for easy reading
results = pd.DataFrame(['cv_mae_val', 'cv_std_val', 'cv_mae_train', 'cv_std_train','holdout_mae','best para'])

In [ ]:
import numpy as np
from sklearn.model_selection import ShuffleSplit, cross_validate

cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=42)

# -----------------------------------------
# 1) CV diagnostics on TRAIN only
#    cross_validate gives train_score and test_score
# -----------------------------------------
best_model = gs_xgb.best_estimator_

cv_out = cross_validate(
    best_model,
    X_train, y_train,
    cv=cv,
    scoring="neg_mean_absolute_error",
    return_train_score=True,
    n_jobs=-1,
    error_score="raise"
)

# Convert negative MAE to positive MAE
val_mae_scores = -cv_out["test_score"]
train_mae_scores = -cv_out["train_score"]

cv_mae_val_mean = float(val_mae_scores.mean())
cv_mae_val_std  = float(val_mae_scores.std())

cv_mae_train_mean = float(train_mae_scores.mean())
cv_mae_train_std  = float(train_mae_scores.std())

# -----------------------------------------
# 2) Holdout MAE (fit once, evaluate once)
# -----------------------------------------
best_model.fit(X_train, y_train)
y_pred = best_model.predict(X_test)
holdout_mae = float(np.mean(np.abs(y_test - y_pred)))

# -----------------------------------------
# 3) Save into results (same 6-row lab book)
# -----------------------------------------
results["XGB_llm_encode_tuned"] = [
    cv_mae_val_mean,
    cv_mae_val_std,
    cv_mae_train_mean,
    cv_mae_train_std,
    holdout_mae,
    gs_xgb.best_params_,
]

display(results)

### Grid search and CV: what to do if time is tight

**Standard definition:**  
Cross-validation (CV) repeats training on different splits to reduce “lucky/unlucky split” effects. Grid search tries multiple hyperparameter settings.

**Practical-test approach (recommended):**
1. Build a baseline model and report results.
2. Improve **one thing only** (for example: class weighting, simpler preprocessing, or a small grid).

If you run the full grid search, note the runtime and what you would do to speed it up.


##Step 9) Error analysis (what to look for)

When you plot predictions or residuals, check:

- Do you systematically over-predict or under-predict?
- Are errors bigger for certain ranges (e.g., predicting 2 or 3 fails)?
- Do you see outliers that might come from data issues?

This is where you decide what to improve next.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# -----------------------------------------
# USER SETTINGS (edit these only)
# -----------------------------------------
sort_col = "Mjob"   # any column in X_test (e.g. "Brand", "GPU", "Screen_Size_inch")
step_n  = 1         # sample every n-th row after sorting

# -----------------------------------------
# 1. Sort by chosen column
# -----------------------------------------
sorted_idx = X_test[sort_col].sort_values().index

X_sorted = X_test.loc[sorted_idx]
y_sorted = y_test.loc[sorted_idx]

# 🔄 XGBoost prediction instead of RF
y_pred_sorted = gs_xgb.best_estimator_.predict(X_sorted)

# Combine into one DataFrame
df_plot = X_sorted.copy()
df_plot["Actual"] = y_sorted.values
df_plot["Predicted"] = y_pred_sorted

# -----------------------------------------
# 2. Apply sampling with iloc[::step_n]
# -----------------------------------------
df_plot = df_plot.iloc[::step_n].reset_index(drop=True)

group_series = df_plot[sort_col]
unique_groups = group_series.unique()

# colour palette based on unique groups
colors = plt.cm.tab10(np.linspace(0, 1, len(unique_groups)))

# Find spans for shading
spans = []
start = 0
for i in range(1, len(group_series)):
    if group_series[i] != group_series[i - 1]:
        spans.append((start, i - 1, group_series[i - 1]))
        start = i
spans.append((start, len(group_series) - 1, group_series.iloc[-1]))

# -----------------------------------------
# 3. Plot with shading + sampled lines
# -----------------------------------------
fig, ax = plt.subplots(figsize=(24, 6))

# Background shading (color spelling is correct)
for idx, (s, e, group_name) in enumerate(spans):
    ax.axvspan(s, e, color=colors[idx % len(colors)], alpha=0.15)

# Actual values
ax.plot(
    df_plot["Actual"].values,
    label=f"Actual (sorted by {sort_col}, sampled every {step_n})",
    color="blue"
)

# Predicted values (XGBoost)
ax.plot(
    df_plot["Predicted"].values,
    label="Predicted (sampled)",
    color="red"
)

ax.set_title(f"Actual vs Predicted Prices — XGBoost (Sorted by {sort_col})")
ax.set_xlabel(f"Sample Index (sorted by {sort_col}, sampled every {step_n})")
ax.set_ylabel("Price (SGD)")
ax.legend()

# Group labels
for idx, (s, e, group_name) in enumerate(spans):
    ax.text(
        (s + e) / 2,
        ax.get_ylim()[1] * 0.98,
        str(group_name),
        ha="center",
        va="top",
        fontsize=9
    )

plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Helper: plot y_true sorted, with y_pred aligned to same order
# ------------------------------------------------------------
def plot_sorted_true_vs_pred(y_true, y_pred_dict, title, xlabel="Sorted sample index"):
    """
    y_true: 1D array-like
    y_pred_dict: dict of {label: y_pred (1D array-like)}
    """
    y_true = np.asarray(y_true).ravel()

    order = np.argsort(y_true)          # indices that would sort y_true
    y_true_sorted = y_true[order]

    plt.figure(figsize=(12, 5))
    plt.plot(y_true_sorted, label="y_true (sorted)")

    for label, y_pred in y_pred_dict.items():
        y_pred = np.asarray(y_pred).ravel()
        plt.plot(y_pred[order], label=f"{label} pred (aligned)")

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Target value")
    plt.legend()
    plt.tight_layout()
    plt.show()


# ------------------------------------------------------------
# 1) Get predictions for TRAIN and TEST for both models
# ------------------------------------------------------------
rf_train_pred  = gs_rf.best_estimator_.predict(X_train)
xgb_train_pred = gs_xgb.best_estimator_.predict(X_train)

rf_test_pred   = gs_rf.best_estimator_.predict(X_test)
xgb_test_pred  = gs_xgb.best_estimator_.predict(X_test)


# ------------------------------------------------------------
# 2) Plot TRAIN: y_train sorted + aligned preds
# ------------------------------------------------------------
plot_sorted_true_vs_pred(
    y_true=y_train,
    y_pred_dict={
        "RF": rf_train_pred,
        "XGB": xgb_train_pred
    },
    title="TRAIN: y_train (sorted) vs RF/XGB predictions (aligned to sorted order)"
)


# ------------------------------------------------------------
# 3) Plot TEST: y_test sorted + aligned preds
# ------------------------------------------------------------
plot_sorted_true_vs_pred(
    y_true=y_test,
    y_pred_dict={
        "RF": rf_test_pred,
        "XGB": xgb_test_pred
    },
    title="TEST: y_test (sorted) vs RF/XGB predictions (aligned to sorted order)"
)

### Early stopping (XGBoost): what it is and why it needs a validation set

**Standard definition:**  
Early stopping stops training when performance on a validation set stops improving, helping to reduce overfitting.

**Important caveat:**  
If you use early stopping, you need a validation set that is not used for fitting the final model at that moment. This is why the notebook creates `X_val, y_val`.

**Alternate interpretation:**  
Some workflows use CV with early stopping inside each fold, but that is more complex and slower. In a practical test, a single validation split is usually enough.


##Step 10) Model improvement (only if time allows)

In a practical test, you only do tuning if it is explicitly requested or you have enough time.

If you tune:
- keep the parameter grid small and sensible
- record best parameters
- re-evaluate on the test set once

**Do not** repeatedly test on the test set. That becomes leakage.

In [ ]:
# ------------------------------------------------------------
# TRAIN / TEST SPLIT
# Keep the test set for final evaluation only.
# ------------------------------------------------------------

%%time
# ============================
# XGBOOST REGRESSION TUNING (GridSearchCV with ShuffleSplit, MAE) + FINAL EARLY STOPPING (single block)
# ============================

import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, ShuffleSplit, train_test_split
from sklearn.metrics import mean_absolute_error, r2_score, root_mean_squared_error

from xgboost import XGBRegressor

# ----------------------------
# 0) Hold-out validation ONLY for final early stopping
# ----------------------------
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train, y_train,
    test_size=0.1,
    random_state=42
)

# ----------------------------
# 1) CV: ShuffleSplit (test_size=0.1)
# ----------------------------
cv = ShuffleSplit(n_splits=5, test_size=0.1, random_state=42)

# ----------------------------
# 2) Pipeline: smaller n_estimators for tuning speed
# ----------------------------
pipe = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(
        random_state=42,
        objective="reg:squarederror",
        tree_method="hist",
        n_jobs=-1,
        n_estimators=200,     # keep modest during GridSearch
        eval_metric="mae"
    ))
])

# ----------------------------
# 3) GridSearch: simple, sensible grid for "most hyperparameters"
#    (keep it small to avoid exploding runtime)
# ----------------------------
param_grid = {
    "regressor__learning_rate": [0.03, 0.05, 0.1],
    "regressor__max_depth": [2, 3, 5],
    "regressor__min_child_weight": [1, 5],
    "regressor__subsample": [0.8, 1.0],
    "regressor__colsample_bytree": [0.8, 1.0],
    "regressor__reg_lambda": [1.0, 5.0],
}

gs = GridSearchCV(
    estimator=pipe,
    param_grid=param_grid,
    scoring="neg_mean_absolute_error",  # MAE (negated because higher-is-better convention)
    cv=cv,
    refit=True,
    n_jobs=-1,
    verbose=1
)

# ----------------------------
# 4) Fit GridSearch on X_tr only
# ----------------------------
gs.fit(X_tr, y_tr)

print("\nGridSearch tuning complete.")
print("Best params:", gs.best_params_)
print("Best CV MAE:", -gs.best_score_)

# ----------------------------
# 5) Final refit with early stopping (based on X_val)
# ----------------------------
best_pipe = gs.best_estimator_
preproc = best_pipe.named_steps["preprocessor"]
best_xgb = best_pipe.named_steps["regressor"]

X_tr_p = preproc.fit_transform(X_tr)
X_val_p = preproc.transform(X_val)
X_test_p = preproc.transform(X_test)

final_params = best_xgb.get_params()
final_params["n_estimators"] = 5000
final_params["eval_metric"] = "mae"
final_params["early_stopping_rounds"] = 100

xgb_final = XGBRegressor(**final_params)
xgb_final.fit(
    X_tr_p, y_tr,
    eval_set=[(X_val_p, y_val)],
    verbose=False
)

# ----------------------------
# 6) Predict using best_iteration when available
# ----------------------------
best_iter = getattr(xgb_final, "best_iteration", None)

if best_iter is not None:
    y_pred = xgb_final.predict(X_test_p, iteration_range=(0, best_iter + 1))
else:
    # Fallback: use all boosted rounds (still OK, just not "best iteration" forced)
    y_pred = xgb_final.predict(X_test_p)

# Optional rounding if target is discrete (e.g. 0..3)
y_pred_round = np.clip(np.rint(y_pred), 0, 3)

print("\nEarly stopping check:")
print("best_iteration:", getattr(xgb_final, "best_iteration", None))
try:
    booster = xgb_final.get_booster()
    print("num_boosted_rounds:", booster.num_boosted_rounds())
except Exception as e:
    print("Could not read booster rounds:", repr(e))

print("\nTEST metrics (raw predictions):")
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", root_mean_squared_error(y_test, y_pred))
print("R^2 :", r2_score(y_test, y_pred))

print("\nTEST metrics (rounded to 0..3, optional):")
print("MAE :", mean_absolute_error(y_test, y_pred_round))
print("RMSE:", root_mean_squared_error(y_test, y_pred_round))
print("R^2 :", r2_score(y_test, y_pred_round))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# Helper: plot y_true sorted, with y_pred aligned to same order
# ------------------------------------------------------------
def plot_sorted_true_vs_pred(y_true, y_pred, title, xlabel="Sorted sample index"):
    y_true = np.asarray(y_true).ravel()
    y_pred = np.asarray(y_pred).ravel()

    order = np.argsort(y_true)
    y_true_sorted = y_true[order]

    plt.figure(figsize=(12, 5))
    plt.plot(y_true_sorted, label="y_true (sorted)")
    plt.plot(y_pred[order], label="best-fit prediction (aligned)")
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("Target value")
    plt.legend()
    plt.tight_layout()
    plt.show()


# ------------------------------------------------------------
# ASSUMES you already ran the fast XGB block above and now have:
# - xgb_final (final early-stopped XGB)
# - preproc   (fitted preprocessor used for xgb_final)
# - X_train, X_test, y_train, y_test
# ------------------------------------------------------------

# Preprocess for xgb_final
X_train_p = preproc.transform(X_train)
X_test_p  = preproc.transform(X_test)

# Best-iteration prediction (version-safe)
best_iter = getattr(xgb_final, "best_iteration", None)
best_ntree_limit = getattr(xgb_final, "best_ntree_limit", None)

if best_iter is not None:
    train_pred = xgb_final.predict(X_train_p, iteration_range=(0, best_iter + 1))
    test_pred  = xgb_final.predict(X_test_p,  iteration_range=(0, best_iter + 1))
elif best_ntree_limit is not None:
    train_pred = xgb_final.predict(X_train_p, ntree_limit=best_ntree_limit)
    test_pred  = xgb_final.predict(X_test_p,  ntree_limit=best_ntree_limit)
else:
    train_pred = xgb_final.predict(X_train_p)
    test_pred  = xgb_final.predict(X_test_p)

# ------------------------------------------------------------
# Plot TRAIN and TEST using best-fit predictions only
# ------------------------------------------------------------
plot_sorted_true_vs_pred(
    y_true=y_train,
    y_pred=train_pred,
    title="TRAIN: y_train (sorted) vs XGB best-fit predictions (aligned)"
)

plot_sorted_true_vs_pred(
    y_true=y_test,
    y_pred=test_pred,
    title="TEST: y_test (sorted) vs XGB best-fit predictions (aligned)"
)